### ISSUE TITLE
`IndexError: Proxy.getblock(): getblock <hash>`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#579]
Running on latest from `develop`:
```
blanket@blanket ~/counterpartyd> python3 counterpartyd.py server
[INFO] Running v9.49.3 of counterpartyd.
[INFO] Connecting to backend.
[INFO] Checking version.
[INFO] Acquiring lock.
[INFO] Connecting to database.
[INFO] Connecting to block explorer.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.3/threading.py", line 637, in _bootstrap_inner
    self.run()
  File "/home/blanket/counterpartyd/lib/api.py", line 373, in run
    app = flask.Flask(__name__)
  File "/usr/local/lib/python3.3/dist-packages/flask/app.py", line 331, in __init__
    instance_path = self.auto_find_instance_path()
  File "/usr/local/lib/python3.3/dist-packages/flask/app.py", line 622, in auto_find_instance_path
    prefix, package_path = find_package(self.import_name)
  File "/usr/local/lib/python3.3/dist-packages/flask/helpers.py", line 682, in find_package
    if loader.is_package(root_mod_name):
AttributeError: 'NamespaceLoader' object has no attribute 'is_package'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/bitcoin/rpc.py", line 239, in getblock
    r = self._call('getblock', block_hash, False)
  File "/usr/local/lib/python3.3/dist-packages/bitcoin/rpc.py", line 146, in _call
    raise JSONRPCException(response['error'])
bitcoin.rpc.JSONRPCException: msg: 'getblock <hash>\nReturns details of a block with given block-hash.'  code: -1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.3/threading.py", line 637, in _bootstrap_inner
    self.run()
  File "/home/blanket/counterpartyd/lib/api.py", line 340, in run
    check.backend_state(self.proxy)
  File "/home/blanket/counterpartyd/lib/check.py", line 139, in backend_state
    cblock = backend.getblock(proxy, block_hash_bin)
  File "/home/blanket/counterpartyd/lib/backend.py", line 38, in getblock
    return proxy.getblock(block_hash_bin)
  File "/usr/local/lib/python3.3/dist-packages/bitcoin/rpc.py", line 242, in getblock
    (self.__class__.__name__, ex.error['message'], ex.error['code']))
IndexError: Proxy.getblock(): getblock <hash>
Returns details of a block with given block-hash. (-1)

[INFO] Resuming parsing.
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/bitcoin/rpc.py", line 239, in getblock
    r = self._call('getblock', block_hash, False)
  File "/usr/local/lib/python3.3/dist-packages/bitcoin/rpc.py", line 146, in _call
    raise JSONRPCException(response['error'])
bitcoin.rpc.JSONRPCException: msg: 'getblock <hash>\nReturns details of a block with given block-hash.'  code: -1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "counterpartyd.py", line 931, in <module>
    blocks.follow(db, proxy)
  File "/home/blanket/counterpartyd/lib/blocks.py", line 897, in follow
    current_cblock = backend.getblock(proxy, current_hash_bin)
  File "/home/blanket/counterpartyd/lib/backend.py", line 38, in getblock
    return proxy.getblock(block_hash_bin)
  File "/usr/local/lib/python3.3/dist-packages/bitcoin/rpc.py", line 242, in getblock
    (self.__class__.__name__, ex.error['message'], ex.error['code']))
IndexError: Proxy.getblock(): getblock <hash>
Returns details of a block with given block-hash. (-1)
```

**Comment by adamkrellenstein** [comment]
Don't know how to reproduce this.

**Comment by adamkrellenstein** [comment]
Can't reproduce, and this might have already been fixed unintentionally.
