### ISSUE TITLE
Bitcoin Core 0.10.0 - wait on "Verifying blocks..."?

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#585]
`v9.49.3 + Bitcoin Core 0.10.0 addrindex`

There's a new feature in Bitcoin Core 0.10.0 whereby it informs RPC requestors that it's started but not ready yet.  
Being able to recognize (and not exit on this response) could help with automatic start of services (e.g. on Fed Node `counterpartyd` could start at the same time as `bitcoind`) so I'm logging this here.

```
C:\Windows\System32>echo off
[INFO] Running v9.49.3 of counterpartyd.←[0m
[INFO] Connecting to backend.←[0m
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "C:\counterpartyd_build\dist\counterpartyd\counterpartyd.py", line 639, i
n <module>
    backend.getblockcount(proxy)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\backend.py", line 34, in g
etblockcount
    return proxy.getblockcount()
  File "C:\counterpartyd_build\env\lib\site-packages\bitcoin\rpc.py", line 160,
in <lambda>
    f = lambda *args: self._call(name, *args)
  File "C:\counterpartyd_build\env\lib\site-packages\bitcoin\rpc.py", line 146,
in _call
    raise JSONRPCException(response['error'])
bitcoin.rpc.JSONRPCException: msg: 'Verifying blocks...'  code: -28←[0m
```

**Comment by adamkrellenstein** [comment]
Solved.
