### ISSUE TITLE
sign_transaction() missing 1 required positional argument

### ISSUE THREAD

**Issue by brighton36** [CounterpartyXCP/counterpartyd#593]
```
[ERROR] API Exception: {'type': 'APIError', 'message': "sign_transaction() missing 1 required positional argument: 'unsigned_tx_hex'", 'args': ("sign_transaction() missing 1 required positional argument: 'unsigned_tx_hex'",)}
Traceback (most recent call last):
  File "/home/cderose/src/counterpartyd_build/dist/counterpartyd/lib/api.py", line 435, in do_method    return do_transaction(db, self.proxy, name=tx, params=transaction_args, private_key_wif=private_key_wif, **common_args)
  File "/home/cderose/src/counterpartyd_build/dist/counterpartyd/lib/api.py", line 300, in do_transaction     signed_tx = sign_transaction(unsigned_tx, private_key_wif=private_key_wif) 
TypeError: sign_transaction() missing 1 required positional argument: 'unsigned_tx_hex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cderose/src/counterpartyd_build/env/lib/python3.4/site-packages/jsonrpc/manager.py", line 89, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/home/cderose/src/counterpartyd_build/dist/counterpartyd/lib/api.py", line 437, in do_method raise APIError(str(e))
lib.api.APIError: sign_transaction() missing 1 required positional argument: 'unsigned_tx_hex'
```

Here's what's being passed as tx_hex in get_tx_info2:
```
01000000010b70dd7033b8d01fb21ae9f1a0322e1a029d1ead79b5be6311efe7a50ee71f50020000001976a9148025b288cb325d88bcd7ef5d1ab1f8827778d5ee88acffffffff02781e000000000000695121021ec8a5efbff400b46ed0516071c0bf2e1b7bddfc95cc7ffbe0fa0df7617ca12d21032dde83a3e995f112f08f2e7d412a0b76e72dbfe950d8f6be9749eb6623c871a1210286b1e4f15de57fd34bde19cf64ad9302e454c4c377677581a951579a124b86e753aee8f2350d000000001976a9148025b288cb325d88bcd7ef5d1ab1f8827778d5ee88ac00000000
```

**Comment by ouziel-slama** [comment]
@brighton36, can you post please the request you did to got this error message?

**Comment by brighton36** [comment]
Seemingly any create request will do this. So, atm I was doing a create_publish. But a create_issuance does this as well

**Comment by brighton36** [comment]
Want access to this system?

**Comment by brighton36** [comment]
FWIW - Went I went back down to .1 the issue went away, so it appears to be something in the newest version
