### ISSUE TITLE
`IndexError` calculating `previous_consensus_hash` on some near?! empty databases

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#599]
```
Traceback (most recent call last):
  File "/home/adam/documents/work/cryptocurrency/counterparty/repositories/counterpartyd/counterpartyd.py", line 936, in <module>
    blocks.follow(db, proxy)
  File "/home/adam/documents/work/cryptocurrency/counterparty/repositories/counterpartyd/lib/blocks.py", line 969, in follow
    parse_block(db, block_index, block_time)
  File "/home/adam/documents/work/cryptocurrency/counterparty/repositories/counterpartyd/lib/blocks.py", line 157, in parse_block
    new_ledger_hash = check.consensus_hash(db, block_index, 'ledger_hash', previous_ledger_hash, util.BLOCK_LEDGER)
  File "/home/adam/documents/work/cryptocurrency/counterparty/repositories/counterpartyd/lib/check.py", line 53, in consensus_hash
    previous_consensus_hash = list(cursor.execute('''SELECT * FROM blocks WHERE block_index = ?''', (block_index - 1,)))[0][field]
IndexError: list index out of range
```

**Comment by adamkrellenstein** [comment]
Not a real issue...
