### ISSUE TITLE
Foreign Key Error with Hard-Coded Burns when Reparsing

### ISSUE THREAD

**Issue by deweller** [CounterpartyXCP/counterpartyd#600]
Here is log info from when the problem started:

```
2015-01-06-T22:51:59+0000 Status: Shutting down.
2015-01-06-T22:52:05+0000 Status: Running v9.49.1 of counterpartyd.
2015-01-06-T22:52:05+0000 Status: Checking version.
2015-01-06-T22:52:06+0000 Status: Acquiring lock.
2015-01-06-T22:52:06+0000 Status: Connecting to database.
2015-01-06-T22:52:46+0000 Status: Connecting to block explorer.
2015-01-06-T22:52:48+0000 Status: Connecting to backend.
2015-01-06-T22:52:48+0000 Status: Resuming parsing.
2015-01-06-T22:52:48+0000 Status: Blockchain reorganisation at block 337825.
2015-01-06-T22:52:48+0000 Status: Reparsing all transactions.
```

I upgraded to 9.49.3 and now I get a Foreign Key error:

```
2015-01-06-T22:59:00+0000 [INFO] Running v9.49.3 of counterpartyd.
2015-01-06-T22:59:00+0000 [INFO] Connecting to backend.
2015-01-06-T22:59:00+0000 [INFO] Checking version.
2015-01-06-T22:59:00+0000 [INFO] Acquiring lock.
2015-01-06-T22:59:00+0000 [INFO] Connecting to database.
2015-01-06-T22:59:40+0000 [INFO] Connecting to block explorer.
2015-01-06-T22:59:42+0000 [INFO] Resuming parsing.
2015-01-06-T22:59:42+0000 [WARNING] Blockchain reorganisation at block 337825.
2015-01-06-T22:59:42+0000 [INFO] Reparsing all transactions.
2015-01-06-T23:00:11+0000 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/counterpartyd.py", line 931, in <module>
    blocks.follow(db, proxy)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 924, in follow
    reparse(db, block_index=current_index-1, quiet=True)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 661, in reparse
    previous_ledger_hash, previous_txlist_hash)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 146, in parse_block
    parse_tx(db, tx)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 67, in parse_tx
    burn.parse(db, tx, MAINNET_BURNS)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/messages/burn.py", line 141, in parse
    burn_parse_cursor.execute(sql, bindings)
  File "src/cursor.c", line 231, in resetcursor
apsw.ConstraintError: ConstraintError: FOREIGN KEY constraint failed
```

Starting counterpartyd results in the FOREIGN KEY error.

Doing a `counterpartyd rollback 337820` also generates a FOREIGN KEY error.

```
[INFO] Block (re‐parse): 278304
[INFO] Block (re‐parse): 278305
[INFO] Block (re‐parse): 278306
[INFO] Block (re‐parse): 278307
[INFO] Block (re‐parse): 278308
[INFO] Block (re‐parse): 278309
[INFO] Block (re‐parse): 278310
[INFO] Block (re‐parse): 278311
[INFO] Block (re‐parse): 278312
[INFO] Block (re‐parse): 278313
[INFO] Block (re‐parse): 278314
[INFO] Block (re‐parse): 278315
[INFO] Block (re‐parse): 278316
[INFO] Block (re‐parse): 278317
[INFO] Block (re‐parse): 278318
[INFO] Block (re‐parse): 278319
[INFO] Burn: 1Pcpxw6wJwXABhjCspe3CNf3gqSeh6eien burned 0.0005 BTC for 0.74959091 XCP (685623401c3f5e9d2eaaf0657a50454e56a270ee7630d409e98d3bc257560098) [valid]
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/counterpartyd.py", line 898, in <module>
    blocks.reparse(db, block_index=args.block_index)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 661, in reparse
    previous_ledger_hash, previous_txlist_hash)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 146, in parse_block
    parse_tx(db, tx)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 67, in parse_tx
    burn.parse(db, tx, MAINNET_BURNS)
  File "/home/ubuntu/counterpartyd_build/dist/counterpartyd/lib/messages/burn.py", line 141, in parse
    burn_parse_cursor.execute(sql, bindings)
  File "src/cursor.c", line 231, in resetcursor
apsw.ConstraintError: ConstraintError: FOREIGN KEY constraint failed
```

**Comment by deweller** [comment]
I ended up deleting this database and starting from the latest counterparty bootstrap database.

**Comment by vennd** [comment]
I got this at block 338076. Re-opening this issue:

[INFO] Running v9.49.3 of counterpartyd.
[INFO] Connecting to backend.
[INFO] Checking version.
[INFO] Acquiring lock.
[INFO] Connecting to database.
[INFO] Connecting to block explorer.
[INFO] Resuming parsing.
[WARNING] Blockchain reorganisation at block 338076.
[INFO] Reparsing all transactions.
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/counterpartyd/counterpartyd_build/dist/counterpartyd/counterpartyd.py", line 931, in <module>
    blocks.follow(db, proxy)
  File "/home/counterpartyd/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 924, in follow
    reparse(db, block_index=current_index-1, quiet=True)
  File "/home/counterpartyd/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 661, in reparse
    previous_ledger_hash, previous_txlist_hash)
  File "/home/counterpartyd/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 146, in parse_block
    parse_tx(db, tx)
  File "/home/counterpartyd/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 67, in parse_tx
    burn.parse(db, tx, MAINNET_BURNS)
  File "/home/counterpartyd/counterpartyd_build/dist/counterpartyd/lib/messages/burn.py", line 141, in parse
    burn_parse_cursor.execute(sql, bindings)
  File "src/cursor.c", line 231, in resetcursor
apsw.ConstraintError: ConstraintError: FOREIGN KEY constraint failed

**Comment by adamkrellenstein** [comment]
@vennd, @deweller, if you do a manual reparse, do you hit the same error?

**Comment by deweller** [comment]
I just did a `counterpartyd reparse`.  There were no errors.

But I did replace my database with a bootstrapped db to work around the problem a couple of days ago.

**Comment by adamkrellenstein** [comment]
@deweller @vennd do you have a copy of a database which gave you the error? If so, can you post it somewhere?

**Comment by deweller** [comment]
Sorry - I was scrambling a bit to get back up and running.  I didn't keep a copy of the problem db.

**Comment by adamkrellenstein** [comment]
Fixed.
