### ISSUE TITLE
`execute past end of script`

### ISSUE THREAD

**Issue by evanwagner1** [CounterpartyXCP/counterpartyd#603]
while running `counterpartyd --testnet server` with btcd:

```
Traceback (most recent call last):
  File "counterpartyd.py", line 936, in <module>
    blocks.follow(db, proxy)
  File "/home/evan/counterpartyd/lib/blocks.py", line 964, in follow
    tx_index = list_tx(db, proxy, block_hash, block_index, block_time, tx_hash, tx_index)
  File "/home/evan/counterpartyd/lib/blocks.py", line 686, in list_tx
    tx_dict = backend.get_cached_raw_transaction(tx_hash, verbose=True)
  File "/usr/lib/python3.4/functools.py", line 458, in wrapper
    result = user_function(*args, **kwds)
  File "/home/evan/counterpartyd/lib/backend.py", line 71, in get_cached_raw_transaction
    return old_rpc('getrawtransaction', [tx_hash, 1])
  File "/home/evan/counterpartyd/lib/backend.py", line 343, in old_rpc
    raise BitcoindError('{}'.format(response_json['error']))
lib.backend.BitcoindError: {'message': 'execute past end of script', 'code': -32603}
```

**Comment by evanwagner1** [comment]
The transaction that btcd is choking on is 12319a73f9ef9f5f88be69806b0cac32967da4d27af6cab0996392211e8bbd9c.

**Comment by evanwagner1** [comment]
```
evan@blanket ~/counterpartyd> btcctl --notls --testnet getrawtransaction 12319a73f9ef9f5f88be69806b0cac32967da4d27af6cab0996392211e8bbd9c 1
rpcCommand: -32603: execute past end of script
```

**Comment by adamkrellenstein** [comment]
```
adam@han ~ > btcctl --testnet --notls getrawtransaction 12319a73f9ef9f5f88be69806b0cac32967da4d27af6cab0996392211e8bbd9c 1
rpcCommand: error getting json reply: error sending json message: Post http://<username>:<password>@localhost:18334: EOF
```

```
2015/01/07 16:19:17 http: panic serving 127.0.0.1:44566: runtime error: invalid memory address or nil pointer dereference
goroutine 22288 [running]:
net/http.func·011()
	/usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0xa326a0, 0xf39273)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
main.handleGetRawTransaction(0xc208060370, 0x7fb841a54520, 0xc2081af1a0, 0xc209a39b00, 0x0, 0x0, 0x0, 0x0)
	/home/adam/go/src/github.com/conformal/btcd/rpcserver.go:2429 +0xb9f
main.standardCmdReply(0x7fb841a54520, 0xc2081af1a0, 0xc208060370, 0xc209a39b00, 0x0, 0x0, 0x0, 0xc2097716a0)
	/home/adam/go/src/github.com/conformal/btcd/rpcserver.go:3280 +0x13d
main.jsonRPCRead(0x7fb841a543f8, 0xc208fb3a40, 0xc2081015f0, 0xc208060370)
	/home/adam/go/src/github.com/conformal/btcd/rpcserver.go:654 +0xbdf
main.func·023(0x7fb841a543f8, 0xc208fb3a40, 0xc2081015f0)
	/home/adam/go/src/github.com/conformal/btcd/rpcserver.go:310 +0x1db
net/http.HandlerFunc.ServeHTTP(0xc20864d080, 0x7fb841a543f8, 0xc208fb3a40, 0xc2081015f0)
	/usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc209469650, 0x7fb841a543f8, 0xc208fb3a40, 0xc2081015f0)
	/usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc208109c80, 0x7fb841a543f8, 0xc208fb3a40, 0xc2081015f0)
	/usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc2084ef900)
	/usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
```

**Comment by adamkrellenstein** [comment]
This is a btcd issue.
