### ISSUE TITLE
counterparty-cli chokes on "market"

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#609]
I run `counterpartyd-cli --testnet market` and it chokes on `TESTASSETONE`:

```
[INFO] Running v9.49.3 of counterpartyd.←[0m
[INFO] Connecting to database.←[0m
Your Pending Order Matches
+------------------+-----------+
| Matched Order ID | Time Left |
+------------------+-----------+
+------------------+-----------+
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 109
2, in <module>
    market(args.give_asset, args.get_asset)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 133
, in market order = format_order(order)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 63,
 in format_order give_quantity = util.value_out(db, D(order['give_quantity']), order['give_as
set'])
  File "c:\counterpartyd_build\dist\counterpartyd\lib\util.py", line 380, in val
ue_out divisible = is_divisible(db, asset)
  File "c:\counterpartyd_build\dist\counterpartyd\lib\util.py", line 338, in is_
divisible if not issuances: raise exceptions.AssetError('No such asset: {}'.format(ass
et))
lib.exceptions.AssetError: No such asset: TESTASSETONE←[0m

```
However there is such an asset 
http://testnet.blockscan.com/asset?q=TESTASSETONE

**Comment by adamkrellenstein** [comment]
This issue was moved to CounterpartyXCP/counterparty-cli#1
