### ISSUE TITLE
counterparty-cli: local variable 'btc_out' referenced before assignment, can with "--unconfirmed"

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#610]
I get this when I try to open a bet from a testnet address.
```
[INFO] Running v9.49.3 of counterpartyd.←[0m
[INFO] Connecting to database.←[0m
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 869
, in <module> args.unsigned)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 232
, in cli unsigned_tx_hex = util.api(method, params)
  File "c:\counterpartyd_build\dist\counterpartyd\lib\util.py", line 69, in api
    raise RPCError('{}'.format(response_json['error']))
lib.util.RPCError: {'message': 'Server error', 'code': -32000, 'data': {'message
': "local variable 'btc_out' referenced before assignment", 'args': ["local vari
able 'btc_out' referenced before assignment"], 'type': 'UnboundLocalError'}}←[0m
```
Then I add `--unconfirmed` and it goes through right away.

**Comment by adamkrellenstein** [comment]
This issue was moved to CounterpartyXCP/counterparty-cli#2
