### ISSUE TITLE
counterpartyd resets continuously on a data-overflow error (testnet)

### ISSUE THREAD

**Issue by curtislacy** [CounterpartyXCP/counterpartyd#615]
I'm seeing this, repeatedly, in my counterpartyd.testnet.log:

```
2015-01-09-T21:23:13+0000 Status: Running v9.49.0 of counterpartyd.
2015-01-09-T21:23:13+0000 Status: Checking version.
2015-01-09-T21:23:13+0000 Status: Acquiring lock.
2015-01-09-T21:23:13+0000 Status: Connecting to database.
2015-01-09-T21:23:13+0000 Status: Connecting to block explorer.
2015-01-09-T21:23:13+0000 Status: Connecting to backend.
2015-01-09-T21:23:13+0000 Status: Resuming parsing.
2015-01-09-T21:23:14+0000 Bet: 0.03 XCP against 0.03 XCP, by mkZ6ECVZYtTE6iGZ6wvBfkw49KLAvsGhCM, on myG2jGS146LntchbNHaAHqPZJyqwqdorUX that ‘SPX, DOW, NASDAQ all in red by EoD today! 1=Y,2=N’ will NotEqual 2.0 at 2015-01-11T05:06:07+00:00, in 500 blocks (68ab7cbf7dd4bdcd31bd009cf3c0576d21b119fa9e3cb6ca154f344a22d0b9dd) [open]
2015-01-09-T21:23:14+0000 Bet Match: Equal for 0.02 XCP against NotEqual for 0.01 XCP on myG2jGS146LntchbNHaAHqPZJyqwqdorUX at 2015-01-11T05:06:07+00:00 that 2.0 value, leveraged 1.0x (cb59ad3f45b794ed270e2963137cf66b84e6b312638ef71b792ce7b5ad70fb6468ab7cbf7dd4bdcd31bd009cf3c0576d21b119fa9e3cb6ca154f344a22d0b9dd) [pending]
2015-01-09-T21:23:14+0000 Bet: 0.03 XCP against 0.03 XCP, by mvBrgbMAucRUQJFJ4Ddjog6FvL4JDQtoPZ, on myG2jGS146LntchbNHaAHqPZJyqwqdorUX that ‘SPX, DOW, NASDAQ all in red by EoD today! 1=Y,2=N’ will Equal 2.0 at 2015-01-11T05:06:07+00:00, in 500 blocks (d11376ff9c7aef79c19c222c9b795cbe58ce654178428c6ddea9df3066163073) [open]
2015-01-09-T21:23:14+0000 Bet Match: NotEqual for 0.02 XCP against Equal for 0.02 XCP on myG2jGS146LntchbNHaAHqPZJyqwqdorUX at 2015-01-11T05:06:07+00:00 that 2.0 value, leveraged 1.0x (68ab7cbf7dd4bdcd31bd009cf3c0576d21b119fa9e3cb6ca154f344a22d0b9ddd11376ff9c7aef79c19c222c9b795cbe58ce654178428c6ddea9df3066163073) [pending]
2015-01-09-T21:23:14+0000 Send: 1 GLDPAMPBRTEN from moNEdvs1YctnA5MNUm9fyRDbzLnE1DmvaA to mwvGWtq51mEHyjoV5783zJXGqmB13ZPaaM (8bc816d788d62732a63da6d174224e0c8e925c35ec7d9a1b428b8e96976e6008) [valid]
2015-01-09-T21:23:14+0000 TX NEW         : tx=<None>, tx_dict={'to': '', 'startgas': 1000000, 'sender': 'mqGf3q3TmSo1HbLium8tgqbxpdFpkXybyN', 'gasprice': 1, 'data': '0x6127103355603c806010600039604c5660003560001a6000811415603a57600135604052602135606052335460605113151560395760605160405154016040515560605133540333555b5b505b6000f3', 'value': 0}
2015-01-09-T21:23:14+0000 MSG APPLY      : sender=mqGf3q3TmSo1HbLium8tgqbxpdFpkXybyN, tx=<None>, gas=913372, value=0, to=9ccf703f124a6aab351448a2a9f4e95848685764, data=0x6127103355603c806010600039604c5660003560001a6000811415603a57600135604052602135606052335460605113151560395760605160405154016040515560605133540333555b5b505b6000f3
2015-01-09-T21:23:14+0000 MSG PRE STATE  : state={'nonce': 0, 'balance': 0, 'storage': [], 'code': '<None>'}, account=9ccf703f124a6aab351448a2a9f4e95848685764
2015-01-09-T21:23:14+0000 STK            : stk=[]
2015-01-09-T21:23:14+0000 OP             : pc=0, op=PUSH2, gas=913372, value=10000, stackargs=[]
2015-01-09-T21:23:14+0000 STK            : stk=[10000]
2015-01-09-T21:23:14+0000 OP             : pc=3, op=CALLER, gas=913371, stackargs=[]
2015-01-09-T21:23:14+0000 STK            : stk=[3244179258947578809808821958818643361977140746904542301701535983509752051799325006, 10000]
2015-01-09-T21:23:14+0000 OP             : pc=4, op=MSTORE8, gas=913370, stackargs=[3244179258947578809808821958818643361977140746904542301701535983509752051799325006, 10000]
2015-01-09-T21:23:14+0000 Execution: mqGf3q3TmSo1HbLium8tgqbxpdFpkXybyN created contract None (72a547ea55293f6f915bfa740ffd2c715435316167b9b7c2da9b5684ccf853cb) [valid]
2015-01-09-T21:23:14+0000 Status: Running v9.49.0 of counterpartyd.
2015-01-09-T21:23:14+0000 Status: Checking version.
2015-01-09-T21:23:15+0000 Status: Acquiring lock.
2015-01-09-T21:23:15+0000 Status: Connecting to database.
2015-01-09-T21:23:15+0000 Status: Connecting to block explorer.
```
I don't know what much of that means, but there's this error reported by sv:

```
File "/home/bitcoin/counterpartyd_build/dist/counterpartyd/lib/messages/scriptlib/processblock.py", line 552, in apply_op     if not mem_extend(mem, compustate, op, s0 + 1):   File "/home/bitcoin/counterpartyd_build/dist/counterpartyd/lib/messages/scriptlib/processblock.py", line 337, in mem_extend     mem.extend([0] * m_extend) OverflowError: cannot fit 'int' into an index-sized integer 
```

**Comment by karlkeefer** [comment]
:+1:

**Comment by adamkrellenstein** [comment]
The continuous restarting is not counterpartyd, but your init system. Rather, counterpartyd was just failing. d4a4c0d should fix the problem. (ffeca79e92898b0def2757a3578d3550b437825e on `master`)

**Comment by curtislacy** [comment]
Hmm, cherry picking that commit onto v9.49.0 resulted in an error, but I half expected that to fail anyway.  
Running from the master branch (ffeca79e92898b0def2757a3578d3550b437825e) fails with:
```
2015-01-10-T02:42:47+0000 [INFO] Running v9.49.3 of counterpartyd.
2015-01-10-T02:42:47+0000 [INFO] Connecting to backend.
2015-01-10-T02:42:47+0000 [INFO] Checking version.
2015-01-10-T02:42:47+0000 [INFO] Acquiring lock.
2015-01-10-T02:42:47+0000 [INFO] Connecting to database.
2015-01-10-T02:42:47+0000 [INFO] Connecting to block explorer.
2015-01-10-T02:42:48+0000 [INFO] Resuming parsing.
2015-01-10-T02:45:19+0000 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/bitcoin/counterpartyd_build/dist/counterpartyd/counterpartyd.py", line 931, in <module>
    blocks.follow(db, proxy)
  File "/home/bitcoin/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 961, in follow
    check.asset_conservation(db)
  File "/home/bitcoin/counterpartyd_build/dist/counterpartyd/lib/check.py", line 84, in asset_conservation
    raise SanityError('{} {} issued ≠ {} {} held'.format(util.value_out(db, issued, asset), asset, util.value_out(db, held, asset), asset))
lib.check.SanityError: 48639.00693195 XCP issued ≠ 48638.99779826 XCP held
```

**Comment by rippler** [comment]
On Windows 7, I overwrote the two files from 9.49.3 with the patched two files and it doesn't seem to work.  I also tried to reinstall from both `master` and `develop`, same outcome.
```
[INFO] Running v9.49.3 of counterpartyd.←[0m
[INFO] Connecting to backend.←[0m
[INFO] Acquiring lock.←[0m
[INFO] Connecting to database.←[0m
[INFO] Reparsing all transactions.←[0m
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "C:\counterpartyd_build\dist\counterpartyd\counterpartyd.py", line 886, i
n <module>
    blocks.reparse(db)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\blocks.py", line 652, in r
eparse
    reinitialise(db, block_index)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\blocks.py", line 613, in r
einitialise
    cursor.execute('''DROP TABLE IF EXISTS {}'''.format(table))
  File "c:\apsw\src\cursor.c", line 231, in resetcursor
apsw.ConstraintError: ConstraintError: FOREIGN KEY constraint failed←[0m
```

**Comment by adamkrellenstein** [comment]
@rippler, @curtislacy, re-clone and do a reparse.

**Comment by adamkrellenstein** [comment]
@rippler @curtislacy, Try using `develop`.

**Comment by adamkrellenstein** [comment]
@ouziel-slama, can you look at this?

**Comment by adamkrellenstein** [comment]
FOREIGN KEYs problem solved.

**Comment by adamkrellenstein** [comment]
Still have the sanity check issue...

**Comment by rippler** [comment]
@adamkrellenstein I did (see my comment above) try both `develop` and `master`. After the 2nd update I deleted the testnet DB and installed from `develop`. Once it gets to 317691, it stops.

```
[INFO] Block: 317691 (0.23s)←[0m
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "C:\counterpartyd_build\dist\counterpartyd\counterpartyd.py", line 931, i
n <module>
    blocks.follow(db, proxy)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\blocks.py", line 961, in f
ollow
    check.asset_conservation(db)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\check.py", line 84, in ass
et_conservation
    raise SanityError('{} {} issued ≠ {} {} held'.format(util.value_out(db, issu
ed, asset), asset, util.value_out(db, held, asset), asset))
lib.check.SanityError: 48639.00693195 XCP issued ≠ 48638.99779826 XCP held←[0m
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\Lib\logging\__init__.py", line 980, in emit
    stream.write(msg)
  File "C:\counterpartyd_build\env\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2260' in position
482: character maps to <undefined>
Call stack:
  File "C:\counterpartyd_build\dist\counterpartyd\counterpartyd.py", line 625, i
n handle_exception
    logger.error("Unhandled Exception", exc_info=(exc_type, exc_value, exc_trace
back))
  File "C:\Python34\Lib\logging\__init__.py", line 1303, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Python34\Lib\logging\__init__.py", line 1409, in _log
    self.handle(record)
  File "C:\Python34\Lib\logging\__init__.py", line 1419, in handle
    self.callHandlers(record)
  File "C:\Python34\Lib\logging\__init__.py", line 1481, in callHandlers
    hdlr.handle(record)
  File "C:\Python34\Lib\logging\__init__.py", line 853, in handle
    self.emit(record)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\util_windows.py", line 23,
 in emit
    logging.handlers.RotatingFileHandler.emit(self, record)
Message: 'Unhandled Exception'
Arguments: ()
```

**Comment by SouKw** [comment]
Could this be bitcoind issue? There is a problem with recent openssl versions breaking Bitcoin Core. http://sourceforge.net/p/bitcoin/mailman/message/33221963/

**Comment by rippler** [comment]
@SouKw I wanted to update my OpenSSL but I haven't yet because I'm on Windows and the guys who release binaries haven't released them yet. Also `counterpartyd` on mainnet running on the same system is not having issues.

**Comment by adamkrellenstein** [comment]
Fixed: https://github.com/ouziel-slama/counterpartyd/commit/10f175e79e029a57bb070ded1bd37bfcd0f12817

**Comment by curtislacy** [comment]
@rippler is this fix working for you?  I'm seeing a DIFFERENT SanityError with edf5091fcacc32abec686a1bfdd1f02c99e7b959 applied, instead of a complete fix:

```
2015-01-12-T19:51:50+0000 [INFO] Running v9.49.3 of counterpartyd.
2015-01-12-T19:51:50+0000 [INFO] Connecting to backend.
2015-01-12-T19:51:50+0000 [INFO] Checking version.
2015-01-12-T19:51:50+0000 [INFO] Acquiring lock.
2015-01-12-T19:51:50+0000 [INFO] Connecting to database.
2015-01-12-T19:51:50+0000 [INFO] Connecting to block explorer.
2015-01-12-T19:51:50+0000 [INFO] Resuming parsing.
2015-01-12-T19:53:03+0000 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/bitcoin/counterpartyd_build/dist/counterpartyd/counterpartyd.py", line 931, in <module>
    blocks.follow(db, proxy)
  File "/home/bitcoin/counterpartyd_build/dist/counterpartyd/lib/blocks.py", line 960, in follow
    check.asset_conservation(db)
  File "/home/bitcoin/counterpartyd_build/dist/counterpartyd/lib/check.py", line 84, in asset_conservation
    raise SanityError('{} {} issued ≠ {} {} held'.format(util.value_out(db, issued, asset), asset, util.value_out(db, held, asset), asset))
lib.check.SanityError: 48639.15682408 XCP issued ≠ 48639.14769039 XCP held
```

**Comment by rippler** [comment]
Curtis, it is working for me but I reinstalled from master and let it recreate the DB because on testnet it's quick and easy.=

**Comment by curtislacy** [comment]
Oof.  Well, if that gets it going again then great.  I worry about what that means for when this stuff rolls out to livenet, though.

**Comment by adamkrellenstein** [comment]
@curtislacy, this isn't close to the final version of the virtual machine.
