### ISSUE TITLE
counterparty-cli: data-dir required, shouldn't be

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#620]
Standalone Windows setup, v.9.49.3.
Problem: without `--data-dir` `counterparty-cli doesn't want to work, although it should because it is specified in my counterpartyd config file. I tried to add `data-dir` to the config file (although that shouldn't be necessary). but that doesn't help either.

```
C:\bitcoin-core-0.10>c:\python34\python.exe c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py --config-file c:\bitcoin-core-0.10\TESTNET.counterpartyd.conf --testnet market
Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 722, in <module>
    testcoin=args.testcoin, force=args.force)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 250, in set_options
    config.DATA_DIR = appdirs.user_config_dir(appauthor=config.XCP_NAME, appname=config.XCP_CLIENT, roaming=True)
AttributeError: 'module' object has no attribute 'user_config_dir'
```

**Comment by rippler** [comment]
Oops, wrong repo. Moving to https://github.com/CounterpartyXCP/counterparty-cli/issues/3
