### ISSUE TITLE
counterpartyd doesn't seem to handle counterblockd's _get_address_history query anymore?

### ISSUE THREAD

**Issue by curtislacy** [CounterpartyXCP/counterpartyd#625]
I'm running the master branch at edf5091fcacc32abec686a1bfdd1f02c99e7b959 on testnet, and since we updated yesterday I'm seeing this in the ```counterblockd.log```:

```
2015-01-13-T15:50:00+0000 API Exception: {'message': "Got back error from server: {u'message': u'Method not found', u'code': -32601}", 'args': ("Got back error from server: {u'message': u'Method not found', u'code': -32601}",), 'type': 'Exception'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jsonrpc/manager.py", line 89, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/home/bitcoin/counterblockd/lib/api.py", line 389, in get_raw_transactions
    d = _get_address_history(address, start_block=start_block_index, end_block=end_block_index)
  File "/home/bitcoin/counterblockd/lib/api.py", line 310, in _get_address_history
    }, abort_on_error=True)['result']
  File "/home/bitcoin/counterblockd/lib/util.py", line 132, in call_jsonrpc_api
    raise Exception("Got back error from server: %s" % result['error'])
Exception: Got back error from server: {u'message': u'Method not found', u'code': -32601}
```

**Comment by rippler** [comment]
Wasn't that moved to `counterparty-cli.py` (use `find` to find if it's not in your path).

**Comment by curtislacy** [comment]
If so, we may have a problem - I'm making this query from my application, and not from the CLI....

**Comment by ouziel-slama** [comment]
@curtislacy: do you run the latest version of counterblockd ?

**Comment by curtislacy** [comment]
Sigh.  I do now, and I'm back in business. Thanks, @ouziel-slama!
