### ISSUE TITLE
counterparty-server.conf data-dir, log-file, api-log-file `~/` error

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#635]
This can be partially fixed by leaving off the leading `~/` from `data-dir` and `log-file` in counterparty-server.conf. This:

```ini
log-file = .counterparty/server.log
api-log-file = .counterparty/api.log
```

instead of:

```ini
log-file = ~/.counterparty/server.log
api-log-file = ~/.counterparty/api.log
```

The latter of which results in:

```bash
$ counterparty-server start
Traceback (most recent call last):
  File "/bin/counterparty-server", line 12, in <module>
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 175, in main
    broadcast_tx_mainnet=broadcast_tx_mainnet)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 281, in initialise
    log.set_up(verbose, logfile=config.LOG)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/log.py", line 39, in set_up
    fileh = logging.handlers.RotatingFileHandler(logfile, maxBytes=max_log_size, backupCount=5)
  File "/usr/lib/python3.4/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.4/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.4/logging/__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/~/.counterparty/server.log'
```

`data-dir` doesn't seem to have any effect when it appears in counterparty-server.conf.

**Comment by adamkrellenstein** [comment]
Re: `FileNotFoundError`, you just can't use `~` there. Unabbreviated absolute paths work, however. (This is the logging module's fault.)

The `data-dir` option in `counterparty-server` has been depreciated. I just removed it: https://github.com/CounterpartyXCP/counterparty-cli/commit/0ccb86eedcd94b2552f5bb97b8c4ba25d3f91647
