### ISSUE TITLE
counterparty-server kickstart error: name 'args' is not defined

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#636]
```bash
$ counterparty-server --verbose kickstart
[INFO] Running v9.49.3 of counterpartyd.
[INFO] Acquiring lock.
[DEBUG] Lock acquired.
[INFO] Connecting to database.
[DEBUG] Creating connection to `counterparty.9.db`.
[DEBUG] Checking database integrity.
[INFO] Connecting to backend.
Traceback (most recent call last):
  File "/bin/counterparty-server", line 12, in <module>
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 185, in main
    server.kickstart(db, bitcoind_dir=args.bitcoind_dir)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 345, in kickstart
    blocks.kickstart(db, bitcoind_dir=args.bitcoind_dir)
NameError: name 'args' is not defined
```

**Comment by adamkrellenstein** [comment]
Solved.
