### ISSUE TITLE
"Ensure that bitcoind is stopped" (kickstart)

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#638]
`counterparty-server kickstart` fails if bitcoind isn't initially running.  Once bitcoind is running, you can start `counterparty-server kickstart`, but afterwards it instructs you to stop running bitcoind before proceeding. If bitcoind isn't running, you have to quickly turn it on and off which doesn't work very well in practice (`bitcoin-cli stop` launches a `bitcoin-shutoff` process which ended up doing nothing for several hours until I eventually `pkill -6`'d bitcoind).

Related logs:

```
2015-01-18-T10:51:32-0800 [INFO] Running v9.49.3 of counterpartyd.
2015-01-18-T10:51:32-0800 [INFO] Acquiring lock.
2015-01-18-T10:51:32-0800 [DEBUG] Lock acquired.
2015-01-18-T10:51:32-0800 [INFO] Connecting to database.
2015-01-18-T10:51:32-0800 [DEBUG] Creating connection to `counterparty.9.db`.
2015-01-18-T10:51:32-0800 [DEBUG] Checking database integrity.
2015-01-18-T10:51:32-0800 [INFO] Connecting to backend.
2015-01-18-T10:51:32-0800 [DEBUG] Could not connect to backend. (Try 1/12)
2015-01-18-T10:51:37-0800 [DEBUG] Could not connect to backend. (Try 2/12)
2015-01-18-T10:51:42-0800 [DEBUG] Could not connect to backend. (Try 3/12)
2015-01-18-T10:51:47-0800 [DEBUG] Could not connect to backend. (Try 4/12)
2015-01-18-T10:51:52-0800 [INFO] Received SIGINT.
2015-01-18-T10:51:52-0800 [INFO] Shutting down.
```

```
2015-01-18-T10:48:31-0800 [INFO] Running v9.49.3 of counterpartyd.
2015-01-18-T10:48:31-0800 [INFO] Acquiring lock.
2015-01-18-T10:48:31-0800 [INFO] Connecting to database.
2015-01-18-T10:48:31-0800 [INFO] Connecting to backend.
2015-01-18-T10:49:31-0800 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 12, in <module>
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 185, in main
    server.kickstart(db, bitcoind_dir=args.bitcoind_dir)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 344, in kickstart
    connect_to_backend()
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 307, in connect_to_backend
    backend.getblockcount()
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/__init__.py", line 32, in getblockcount
    return BACKEND().getblockcount()
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/addrindex.py", line 118, in getblockcount
    return rpc('getblockcount', [])
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/addrindex.py", line 52, in rpc
    raise BackendRPCError('Cannot communicate with backend. ({} is set to run on {}, is backend?)'.format(config.XCP_CLIENT, network))
counterpartylib.lib.backend.addrindex.BackendRPCError: Cannot communicate with backend. (counterpartyd is set to run on mainnet, is backend?)
```

As an aside, could the `(y/N)` prompt be worked around with something like:

```python
parser_kickstart.add_argument('--noconfirm', help='do not prompt for any confirmation')
```

That would make it easier to run kickstart from system service files / configuration management frameworks.

**Comment by adamkrellenstein** [comment]
Solved. Thanks!

**Comment by atweiden** [comment]
Source | AUR
---    | ---
[bitcoin-headless-addrindex](https://github.com/atweiden/pkgbuilds/tree/master/bitcoin-headless-addrindex) | https://aur.archlinux.org/packages/bitcoin-headless-addrindex/
[bitcoin-qt-addrindex](https://github.com/atweiden/pkgbuilds/tree/master/bitcoin-qt-addrindex) | https://aur.archlinux.org/packages/bitcoin-qt-addrindex/
[python-counterparty-lib](https://github.com/atweiden/pkgbuilds/tree/master/python-counterparty-lib) | https://aur.archlinux.org/packages/python-counterparty-lib/
[python-counterparty-lib-git](https://github.com/atweiden/pkgbuilds/tree/master/python-counterparty-lib-git) | https://aur.archlinux.org/packages/python-counterparty-lib-git/
[counterparty-cli](https://github.com/atweiden/pkgbuilds/tree/master/counterparty-cli) | https://aur.archlinux.org/packages/counterparty-cli/
[counterparty-cli-git](https://github.com/atweiden/pkgbuilds/tree/master/counterparty-cli-git) | https://aur.archlinux.org/packages/counterparty-cli-git/
[counterparty-gui](https://github.com/atweiden/pkgbuilds/tree/master/counterparty-gui) | https://aur.archlinux.org/packages/counterparty-gui/
[counterparty-gui-git](https://github.com/atweiden/pkgbuilds/tree/master/counterparty-gui-git) | https://aur.archlinux.org/packages/counterparty-gui-git/

**Comment by adamkrellenstein** [comment]
@atweiden, very cool!
