### ISSUE TITLE
counterparty-server kickstart reparse error: Incorrect ledger_hash

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#639]
```
[INFO] Block (re‐parse): 334000
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 12, in <module>
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 185, in main
    server.kickstart(db, bitcoind_dir=args.bitcoind_dir)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 345, in kickstart
    blocks.kickstart(db, bitcoind_dir=bitcoind_dir)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 832, in kickstart
    reparse(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 673, in reparse
    previous_ledger_hash, previous_txlist_hash)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 159, in parse_block
    new_ledger_hash = check.consensus_hash(db, 'ledger_hash', previous_ledger_hash, util.BLOCK_LEDGER)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/check.py", line 80, in consensus_hash
    raise ConsensusError('Incorrect {} for block {}.'.format(field, block_index))
counterpartylib.lib.check.ConsensusError: Incorrect ledger_hash for block 334000.
[1]+  Aborted                 (core dumped) bitcoind
```

**Comment by adamkrellenstein** [comment]
@atweiden, can you host a copy of the bad database somewhere, so I can look at it?

**Comment by adamkrellenstein** [comment]
And did you shut down `bitcoind` before running `kickstart`? (It looks like `bitcoind` crashed while you were kickstarting.)

**Comment by ouziel-slama** [comment]
Also can you confirm please that you ran the `kickstart` with the `develop` branch ?

**Comment by atweiden** [comment]
This was run prior to https://github.com/CounterpartyXCP/counterpartyd/commit/8618d6f2ab77e6094c98dd69835de29a4744a559 on `develop`. I had to `kill -6` bitcoind after briefly starting it up so that `counterparty-server` could do a backend connect (now unnecesary).

[Crashed db](https://www.filepicker.io/api/file/6u646RSjCTHWgkySmvsw). I guess after `counterparty-server` crashed, the db became 1kb so dunno if it will help.

I'm retesting with the latest develop on [python-counterparty-lib-git](https://aur.archlinux.org/packages/python-counterparty-lib-git/) and [counterparty-cli-git](https://aur.archlinux.org/packages/counterparty-cli-git/) after rebooting.

**Comment by adamkrellenstein** [comment]
@ouziel-slama, #640 solves this?

**Comment by adamkrellenstein** [comment]
@atweiden 8618d6f won't fix the bug in question, just the requirement to start and restart Bitcoin Core.

**Comment by ouziel-slama** [comment]
@adamkrellenstein, yes I think it solves this. I will confirm as soon the kickstart is finished..

**Comment by atweiden** [comment]
It's still crashing with the same error for me.

**Comment by adamkrellenstein** [comment]
@atweiden, that's with https://github.com/CounterpartyXCP/counterpartyd/commit/b431a8e7d8d039a66b3f9ebcc00c2de7a128932f?

**Comment by atweiden** [comment]
It wasn't, but the issue remains with the newer commit:

```
[INFO] Block (re‐parse): 334000
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 12, in <module>
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 182, in main
    server.kickstart(db, bitcoind_dir=args.bitcoind_dir)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 341, in kickstart
    blocks.kickstart(db, bitcoind_dir=bitcoind_dir)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 833, in kickstart
    reparse(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 674, in reparse
    previous_ledger_hash, previous_txlist_hash)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 159, in parse_block
    new_ledger_hash = check.consensus_hash(db, 'ledger_hash', previous_ledger_hash, util.BLOCK_LEDGER)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/check.py", line 80, in consensus_hash
    raise ConsensusError('Incorrect {} for block {}.'.format(field, block_index))
counterpartylib.lib.check.ConsensusError: Incorrect ledger_hash for block 334000.
```

**Comment by ouziel-slama** [comment]
OK the kickstart is finished and I confirm that https://github.com/CounterpartyXCP/counterpartyd/commit/8f4277fce1a7212df0037182a807ff5ba745c13d fixes this issue.

**Comment by atweiden** [comment]
I also confirm this issue is solved by https://github.com/CounterpartyXCP/counterpartyd/commit/8f4277fce1a7212df0037182a807ff5ba745c13d.

Is there any way to kickstart `counterparty-server` that avoids having to run `bitcoind -reindex` afterwards?

**Comment by ouziel-slama** [comment]
@atweiden: unfortunately I don't know a way to avoid the `reindex`. I hope there is one.. as soon as I get a chance I will work on this.
