### ISSUE TITLE
counterparty-lib: lots of inconsistent linkage

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#657]
I haven't seen this with other modules. Should I run some tests to see if things work as expected?
I have Win32 OpenSSL v1.0.1L Light installed, in addition to MSVC. 
Other: Windows 8.1, 32-bit, Python 3.4 32-bit.

```
    C:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /
INCREMENTAL:NO /LIBPATH:C:\Python34\libs /LIBPATH:C:\Python34\PCbuild /EXPORT:Py
Init__CAST build\temp.win32-3.4\Release\src/CAST.obj /OUT:build\lib.win32-3.4\Cr
ypto\Cipher\_CAST.pyd /IMPLIB:build\temp.win32-3.4\Release\src\_CAST.lib /MANIFE
STFILE:build\temp.win32-3.4\Release\src\_CAST.pyd.manifest
       Creating library build\temp.win32-3.4\Release\src\_CAST.lib and object bu
ild\temp.win32-3.4\Release\src\_CAST.exp
    building 'Crypto.Cipher._DES' extension
    C:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /
MD /W3 /GS- /DNDEBUG -Isrc/ -Isrc/libtom/ -Isrc/inc-msvc/ -IC:\Python34\include
-IC:\Python34\include /Tcsrc/DES.c /Fobuild\temp.win32-3.4\Release\src/DES.obj
    DES.c
    src/libtom/tomcrypt_cfg.h(26) : warning C4273: 'malloc' : inconsistent dll l
inkage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(60
0) : see previous definition of 'malloc'
    src/libtom/tomcrypt_cfg.h(27) : warning C4273: 'realloc' : inconsistent dll
linkage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(60
2) : see previous definition of 'realloc'
    src/libtom/tomcrypt_cfg.h(28) : warning C4273: 'calloc' : inconsistent dll l
inkage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(59
8) : see previous definition of 'calloc'
    src/libtom/tomcrypt_cfg.h(29) : warning C4273: 'free' : inconsistent dll lin
kage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(59
9) : see previous definition of 'free'
    src/libtom/tomcrypt_cfg.h(31) : warning C4273: 'qsort' : inconsistent dll li
nkage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(42
5) : see previous definition of 'qsort'
    src/libtom/tomcrypt_cfg.h(35) : warning C4273: 'clock' : inconsistent dll li
nkage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\time.h(163)
 : see previous definition of 'clock'
    C:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /
INCREMENTAL:NO /LIBPATH:C:\Python34\libs /LIBPATH:C:\Python34\PCbuild /EXPORT:Py
Init__DES build\temp.win32-3.4\Release\src/DES.obj /OUT:build\lib.win32-3.4\Cryp
to\Cipher\_DES.pyd /IMPLIB:build\temp.win32-3.4\Release\src\_DES.lib /MANIFESTFI
LE:build\temp.win32-3.4\Release\src\_DES.pyd.manifest
       Creating library build\temp.win32-3.4\Release\src\_DES.lib and object bui
ld\temp.win32-3.4\Release\src\_DES.exp
    building 'Crypto.Cipher._DES3' extension
    C:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /
MD /W3 /GS- /DNDEBUG -Isrc/ -Isrc/libtom/ -Isrc/inc-msvc/ -IC:\Python34\include
-IC:\Python34\include /Tcsrc/DES3.c /Fobuild\temp.win32-3.4\Release\src/DES3.obj

    DES3.c
    src/libtom/tomcrypt_cfg.h(26) : warning C4273: 'malloc' : inconsistent dll l
inkage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(60
0) : see previous definition of 'malloc'
    src/libtom/tomcrypt_cfg.h(27) : warning C4273: 'realloc' : inconsistent dll
linkage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(60
2) : see previous definition of 'realloc'
    src/libtom/tomcrypt_cfg.h(28) : warning C4273: 'calloc' : inconsistent dll l
inkage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(59
8) : see previous definition of 'calloc'
    src/libtom/tomcrypt_cfg.h(29) : warning C4273: 'free' : inconsistent dll lin
kage
            C:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(59
9) : see previous definition of 'free'
    src/libtom/tomcrypt_cfg.h(31) : warning C4273: 'qsort' : inconsistent dll li
nkage
```

**Comment by adamkrellenstein** [comment]
@robby-dermody, any idea what this is?

**Comment by robby-dermody** [comment]
looks like there may be multiple stdlibs the linker is going off of?

EDIT: yes, looks like something with include order, and or conflicting link libraries with the required routine exports? (https://github.com/ThrowTheSwitch/Unity/issues/24#issuecomment-12051306 is the closest thing I can find)

**Comment by robby-dermody** [comment]
what specifically is he trying to build here, pycrypto?

If it was something we did, I would say to fiddle with the include order of `stdlib.h`

**Comment by rippler** [comment]
@robby-dermody good question that. The log had several hundred lines so I didn't want to paste it whole but I should have at least captured the command and the first few lines. I think I couldn't build `counterparty-lib` because some packages were missing, and once I did install them, I would get error like that. I'll see if I can find more in `pip.log` on the other system where I did this. 

FWIW here's how I just installed `counterpartyd` from `develop` on Windows 7 with Python 3.4:
* Download the Zip archive with `counterpartyd` source code from `develop` branch
* If installing on a system with `counterpartyd` v9.49.3 or older, upgrade `appdirs`: `pip install --upgrade appdirs`
* Unzip downloaded source code, navigate to its top level directory and install it with `C:\python34\python.exe setup.py install`

If I don't update this within couple of days we can close this issue.

**Comment by rippler** [comment]
I tried again on another system (this one has MS VC 2010). I think I know why I've been seeing all these errors: because normally we install a binary PyCrypto package and here that wasn't mentioned so it failed on a clean system. I used `pip install counterpaty-lib`, by the way. 

I think we should confirm what Python binaries should be installed before `counterparty-lib` is installed (maybe the same as before, but maybe we'd need additional ones). I created another issue for that here:https://github.com/CounterpartyXCP/federatednode_build/issues/193 so I'll close this one.

```
Downloading/unpacking counterparty-lib

  Getting page https://pypi.python.org/simple/counterparty-lib/
  URLs to search for versions for counterparty-lib:
  * https://pypi.python.org/simple/counterparty-lib/
  Analyzing links from page https://pypi.python.org/simple/counterparty-lib/
    Found link https://pypi.python.org/packages/source/c/counterparty-lib/counterparty-lib-9.49.3.tar.gz#md5=cd51eb61ddb509f411d5767e906c82b5 (from https://pypi.python.org/simple/counterparty-lib/), version: 9.49.3
    Found link https://pypi.python.org/packages/source/c/counterparty-lib/counterparty-lib-9.49.4.tar.gz#md5=84f09c9da32fd0c891825aa3d01fc540 (from https://pypi.python.org/simple/counterparty-lib/), version: 9.49.4
  Using version 9.49.4 (newest of versions: 9.49.4, 9.49.3)
  Downloading from URL https://pypi.python.org/packages/source/c/counterparty-lib/counterparty-lib-9.49.4.tar.gz#md5=84f09c9da32fd0c891825aa3d01fc540 (from https://pypi.python.org/simple/counterparty-lib/)
  Running setup.py egg_info for package counterparty-lib

    running egg_info
    creating pip-egg-info\counterparty_lib.egg-info
    writing top-level names to pip-egg-info\counterparty_lib.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\counterparty_lib.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\counterparty_lib.egg-info\requires.txt
    writing pip-egg-info\counterparty_lib.egg-info\PKG-INFO
    writing manifest file 'pip-egg-info\counterparty_lib.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info\counterparty_lib.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info\counterparty_lib.egg-info\SOURCES.txt'
    WARNING:root:Warning:

    To complete the installation you have to install:

    - APSW: https://github.com/rogerbinns/apsw/releases

    - Serpent: https://github.com/ethereum/serpent

  Source in c:\users\rippler\appdata\local\temp\pip_build_rippler\counterparty-lib has version 9.49.4, which satisfies requirement counterparty-lib
Downloading/unpacking appdirs==1.4.0 (from counterparty-lib)


....


    running build_ext
    building 'Crypto.Random.OSRNG.winrandom' extension

    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pycrypto\setup.py", line 456, in <module>

        core.setup(**kw)

      File "C:\Python34\lib\distutils\core.py", line 148, in setup

        dist.run_commands()

      File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands

        self.run_command(cmd)

      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 54, in run

        return _install.run(self)

      File "C:\Python34\lib\distutils\command\install.py", line 554, in run

        self.run_command('build')

      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Python34\lib\distutils\command\build.py", line 126, in run

        self.run_command(cmd_name)

      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pycrypto\setup.py", line 253, in run

        build_ext.run(self)

      File "C:\Python34\lib\distutils\command\build_ext.py", line 348, in run

        self.build_extensions()

      File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pycrypto\setup.py", line 150, in build_extensions

        build_ext.build_extensions(self)

      File "C:\Python34\lib\distutils\command\build_ext.py", line 457, in build_extensions

        self.build_extension(ext)

      File "C:\Python34\lib\distutils\command\build_ext.py", line 512, in build_extension

        depends=ext.depends)

      File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile

        self.initialize()

      File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)

      File "C:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall

        raise ValueError(str(list(result.keys())))

    ValueError: ['path']

    Complete output from command C:\Python34\python.exe -c "import setuptools;__file__='C:\\Users\\rippler\\AppData\\Local\\Temp\\pip_build_rippler\\pycrypto\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\rippler\AppData\Local\Temp\pip-abbu9nl3-record\install-record.txt --single-version-externally-managed:

    running install

running build

running build_py

creating build

creating build\lib.win-amd64-3.4

creating build\lib.win-amd64-3.4\Crypto

copying lib\Crypto\pct_warnings.py -> build\lib.win-amd64-3.4\Crypto

copying lib\Crypto\__init__.py -> build\lib.win-amd64-3.4\Crypto

creating build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\hashalgo.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\HMAC.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\MD2.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\MD4.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\MD5.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\RIPEMD.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\SHA.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\SHA224.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\SHA256.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\SHA384.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\SHA512.py -> build\lib.win-amd64-3.4\Crypto\Hash

copying lib\Crypto\Hash\__init__.py -> build\lib.win-amd64-3.4\Crypto\Hash

creating build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\AES.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\ARC2.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\ARC4.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\blockalgo.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\Blowfish.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\CAST.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\DES.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\DES3.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\PKCS1_OAEP.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\PKCS1_v1_5.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\XOR.py -> build\lib.win-amd64-3.4\Crypto\Cipher

copying lib\Crypto\Cipher\__init__.py -> build\lib.win-amd64-3.4\Crypto\Cipher

creating build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\asn1.py -> build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\Counter.py -> build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\number.py -> build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\py3compat.py -> build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\randpool.py -> build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\RFC1751.py -> build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\winrandom.py -> build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\_number_new.py -> build\lib.win-amd64-3.4\Crypto\Util

copying lib\Crypto\Util\__init__.py -> build\lib.win-amd64-3.4\Crypto\Util

creating build\lib.win-amd64-3.4\Crypto\Random

copying lib\Crypto\Random\random.py -> build\lib.win-amd64-3.4\Crypto\Random

copying lib\Crypto\Random\_UserFriendlyRNG.py -> build\lib.win-amd64-3.4\Crypto\Random

copying lib\Crypto\Random\__init__.py -> build\lib.win-amd64-3.4\Crypto\Random

creating build\lib.win-amd64-3.4\Crypto\Random\Fortuna

copying lib\Crypto\Random\Fortuna\FortunaAccumulator.py -> build\lib.win-amd64-3.4\Crypto\Random\Fortuna

copying lib\Crypto\Random\Fortuna\FortunaGenerator.py -> build\lib.win-amd64-3.4\Crypto\Random\Fortuna

copying lib\Crypto\Random\Fortuna\SHAd256.py -> build\lib.win-amd64-3.4\Crypto\Random\Fortuna

copying lib\Crypto\Random\Fortuna\__init__.py -> build\lib.win-amd64-3.4\Crypto\Random\Fortuna

creating build\lib.win-amd64-3.4\Crypto\Random\OSRNG

copying lib\Crypto\Random\OSRNG\fallback.py -> build\lib.win-amd64-3.4\Crypto\Random\OSRNG

copying lib\Crypto\Random\OSRNG\nt.py -> build\lib.win-amd64-3.4\Crypto\Random\OSRNG

copying lib\Crypto\Random\OSRNG\posix.py -> build\lib.win-amd64-3.4\Crypto\Random\OSRNG

copying lib\Crypto\Random\OSRNG\rng_base.py -> build\lib.win-amd64-3.4\Crypto\Random\OSRNG

copying lib\Crypto\Random\OSRNG\__init__.py -> build\lib.win-amd64-3.4\Crypto\Random\OSRNG

creating build\lib.win-amd64-3.4\Crypto\SelfTest

copying lib\Crypto\SelfTest\st_common.py -> build\lib.win-amd64-3.4\Crypto\SelfTest

copying lib\Crypto\SelfTest\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest

creating build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\common.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_AES.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_ARC2.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_ARC4.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_Blowfish.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_CAST.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_DES.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_DES3.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_pkcs1_15.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_pkcs1_oaep.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\test_XOR.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

copying lib\Crypto\SelfTest\Cipher\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Cipher

creating build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\common.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_HMAC.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_MD2.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_MD4.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_MD5.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_RIPEMD.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_SHA.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_SHA224.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_SHA256.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_SHA384.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\test_SHA512.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

copying lib\Crypto\SelfTest\Hash\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Hash

creating build\lib.win-amd64-3.4\Crypto\SelfTest\Protocol

copying lib\Crypto\SelfTest\Protocol\test_AllOrNothing.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Protocol

copying lib\Crypto\SelfTest\Protocol\test_chaffing.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Protocol

copying lib\Crypto\SelfTest\Protocol\test_KDF.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Protocol

copying lib\Crypto\SelfTest\Protocol\test_rfc1751.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Protocol

copying lib\Crypto\SelfTest\Protocol\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Protocol

creating build\lib.win-amd64-3.4\Crypto\SelfTest\PublicKey

copying lib\Crypto\SelfTest\PublicKey\test_DSA.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\PublicKey

copying lib\Crypto\SelfTest\PublicKey\test_ElGamal.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\PublicKey

copying lib\Crypto\SelfTest\PublicKey\test_importKey.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\PublicKey

copying lib\Crypto\SelfTest\PublicKey\test_RSA.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\PublicKey

copying lib\Crypto\SelfTest\PublicKey\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\PublicKey

creating build\lib.win-amd64-3.4\Crypto\SelfTest\Random

copying lib\Crypto\SelfTest\Random\test_random.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random

copying lib\Crypto\SelfTest\Random\test_rpoolcompat.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random

copying lib\Crypto\SelfTest\Random\test__UserFriendlyRNG.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random

copying lib\Crypto\SelfTest\Random\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random

creating build\lib.win-amd64-3.4\Crypto\SelfTest\Random\Fortuna

copying lib\Crypto\SelfTest\Random\Fortuna\test_FortunaAccumulator.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\Fortuna

copying lib\Crypto\SelfTest\Random\Fortuna\test_FortunaGenerator.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\Fortuna

copying lib\Crypto\SelfTest\Random\Fortuna\test_SHAd256.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\Fortuna

copying lib\Crypto\SelfTest\Random\Fortuna\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\Fortuna

creating build\lib.win-amd64-3.4\Crypto\SelfTest\Random\OSRNG

copying lib\Crypto\SelfTest\Random\OSRNG\test_fallback.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\OSRNG

copying lib\Crypto\SelfTest\Random\OSRNG\test_generic.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\OSRNG

copying lib\Crypto\SelfTest\Random\OSRNG\test_nt.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\OSRNG

copying lib\Crypto\SelfTest\Random\OSRNG\test_posix.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\OSRNG

copying lib\Crypto\SelfTest\Random\OSRNG\test_winrandom.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\OSRNG

copying lib\Crypto\SelfTest\Random\OSRNG\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Random\OSRNG

creating build\lib.win-amd64-3.4\Crypto\SelfTest\Util

copying lib\Crypto\SelfTest\Util\test_asn1.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Util

copying lib\Crypto\SelfTest\Util\test_Counter.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Util

copying lib\Crypto\SelfTest\Util\test_number.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Util

copying lib\Crypto\SelfTest\Util\test_winrandom.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Util

copying lib\Crypto\SelfTest\Util\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Util

creating build\lib.win-amd64-3.4\Crypto\SelfTest\Signature

copying lib\Crypto\SelfTest\Signature\test_pkcs1_15.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Signature

copying lib\Crypto\SelfTest\Signature\test_pkcs1_pss.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Signature

copying lib\Crypto\SelfTest\Signature\__init__.py -> build\lib.win-amd64-3.4\Crypto\SelfTest\Signature

creating build\lib.win-amd64-3.4\Crypto\Protocol

copying lib\Crypto\Protocol\AllOrNothing.py -> build\lib.win-amd64-3.4\Crypto\Protocol

copying lib\Crypto\Protocol\Chaffing.py -> build\lib.win-amd64-3.4\Crypto\Protocol

copying lib\Crypto\Protocol\KDF.py -> build\lib.win-amd64-3.4\Crypto\Protocol

copying lib\Crypto\Protocol\__init__.py -> build\lib.win-amd64-3.4\Crypto\Protocol

creating build\lib.win-amd64-3.4\Crypto\PublicKey

copying lib\Crypto\PublicKey\DSA.py -> build\lib.win-amd64-3.4\Crypto\PublicKey

copying lib\Crypto\PublicKey\ElGamal.py -> build\lib.win-amd64-3.4\Crypto\PublicKey

copying lib\Crypto\PublicKey\pubkey.py -> build\lib.win-amd64-3.4\Crypto\PublicKey

copying lib\Crypto\PublicKey\RSA.py -> build\lib.win-amd64-3.4\Crypto\PublicKey

copying lib\Crypto\PublicKey\_DSA.py -> build\lib.win-amd64-3.4\Crypto\PublicKey

copying lib\Crypto\PublicKey\_RSA.py -> build\lib.win-amd64-3.4\Crypto\PublicKey

copying lib\Crypto\PublicKey\_slowmath.py -> build\lib.win-amd64-3.4\Crypto\PublicKey

copying lib\Crypto\PublicKey\__init__.py -> build\lib.win-amd64-3.4\Crypto\PublicKey

creating build\lib.win-amd64-3.4\Crypto\Signature

copying lib\Crypto\Signature\PKCS1_PSS.py -> build\lib.win-amd64-3.4\Crypto\Signature

copying lib\Crypto\Signature\PKCS1_v1_5.py -> build\lib.win-amd64-3.4\Crypto\Signature

copying lib\Crypto\Signature\__init__.py -> build\lib.win-amd64-3.4\Crypto\Signature

Skipping implicit fixer: buffer

Skipping implicit fixer: idioms

Skipping implicit fixer: set_literal

Skipping implicit fixer: ws_comma

running build_ext

building 'Crypto.Random.OSRNG.winrandom' extension

warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pycrypto\setup.py", line 456, in <module>

    core.setup(**kw)

  File "C:\Python34\lib\distutils\core.py", line 148, in setup

    dist.run_commands()

  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

    cmd_obj.run()

  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 54, in run

    return _install.run(self)

  File "C:\Python34\lib\distutils\command\install.py", line 554, in run

    self.run_command('build')

  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

    cmd_obj.run()

  File "C:\Python34\lib\distutils\command\build.py", line 126, in run

    self.run_command(cmd_name)

  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

    cmd_obj.run()

  File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pycrypto\setup.py", line 253, in run

    build_ext.run(self)

  File "C:\Python34\lib\distutils\command\build_ext.py", line 348, in run

    self.build_extensions()

  File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pycrypto\setup.py", line 150, in build_extensions

    build_ext.build_extensions(self)

  File "C:\Python34\lib\distutils\command\build_ext.py", line 457, in build_extensions

    self.build_extension(ext)

  File "C:\Python34\lib\distutils\command\build_ext.py", line 512, in build_extension

    depends=ext.depends)

  File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile

    self.initialize()

  File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize

    vc_env = query_vcvarsall(VERSION, plat_spec)

  File "C:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall

    raise ValueError(str(list(result.keys())))

ValueError: ['path']

----------------------------------------

Cleaning up...

  Removing temporary dir C:\Users\rippler\AppData\Local\Temp\pip_build_rippler...
Command C:\Python34\python.exe -c "import setuptools;__file__='C:\\Users\\rippler\\AppData\\Local\\Temp\\pip_build_rippler\\pycrypto\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\rippler\AppData\Local\Temp\pip-abbu9nl3-record\install-record.txt --single-version-externally-managed failed with error code 1 in C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pycrypto

Exception information:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\basecommand.py", line 134, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\commands\install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\req.py", line 1298, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\req.py", line 625, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command C:\Python34\python.exe -c "import setuptools;__file__='C:\\Users\\rippler\\AppData\\Local\\Temp\\pip_build_rippler\\pycrypto\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\rippler\AppData\Local\Temp\pip-abbu9nl3-record\install-record.txt --single-version-externally-managed failed with error code 1 in C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pycrypto
```
