### ISSUE TITLE
counterparty-lib: python-bitcoinlib==0.3.0 not available

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#661]
* Win 7 x64 
* Python 3.4.2 x32
* PyCrypto 2.6.1 (binary package)
*  Command: `pip install counterparty-lib`

```
Downloading/unpacking colorlog==2.4.0 (from counterparty-lib)
  Downloading colorlog-2.4.0-py2.py3-none-any.whl
Downloading/unpacking python-bitcoinlib==0.3.0 (from counterparty-lib)
  Could not find a version that satisfies the requirement python-bitcoinlib==0.3
.0 (from counterparty-lib) (from versions: 0.1.1, 0.2.0, 0.2.1)
Cleaning up...
No distributions matching the version for python-bitcoinlib==0.3.0 (from counter
party-lib)
Storing debug log for failure in C:\Users\rippler\pip\pip.log

```

From `pip.log`:
```
C:\Python34\Scripts\pip run on 01/25/15 16:15:35
Requirement already satisfied (use --upgrade to upgrade): counterparty-lib in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): appdirs==1.4.0 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): prettytable==0.7.2 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.2 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): flask==0.10.1 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): json-rpc==1.7 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pytest==2.6.3 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pycoin==0.52 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): requests==2.4.2 in c:\python34\lib\site-packages (from counterparty-lib)
  skipping extra security
  skipping extra security
  skipping extra security
Requirement already satisfied (use --upgrade to upgrade): Flask-HTTPAuth==2.3.0 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): tornado==4.0.2 in c:\python34\lib\site-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6.1 in c:\python34\lib\site-packages (from counterparty-lib)
Downloading/unpacking tendo==0.2.6 (from counterparty-lib)

...

Downloading/unpacking python-bitcoinlib==0.3.0 (from counterparty-lib)
  Getting page https://pypi.python.org/simple/python-bitcoinlib/
  URLs to search for versions for python-bitcoinlib==0.3.0 (from counterparty-lib):
  * https://pypi.python.org/simple/python-bitcoinlib/0.3.0
  * https://pypi.python.org/simple/python-bitcoinlib/
  Getting page https://pypi.python.org/simple/python-bitcoinlib/0.3.0
  Could not fetch URL https://pypi.python.org/simple/python-bitcoinlib/0.3.0: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/python-bitcoinlib/0.3.0 when looking for download links for python-bitcoinlib==0.3.0 (from counterparty-lib)
  Analyzing links from page https://pypi.python.org/simple/python-bitcoinlib/
    Found link https://pypi.python.org/packages/source/p/python-bitcoinlib/python-bitcoinlib-0.1.1.tar.gz#md5=b0dd501ac3f961401327ca4320946218 (from https://pypi.python.org/simple/python-bitcoinlib/), version: 0.1.1
    Found link https://pypi.python.org/packages/source/p/python-bitcoinlib/python-bitcoinlib-0.2.0.tar.gz#md5=2a87f139db530ad299a123ddba8b981f (from https://pypi.python.org/simple/python-bitcoinlib/), version: 0.2.0
    Found link https://pypi.python.org/packages/source/p/python-bitcoinlib/python-bitcoinlib-0.2.1.tar.gz#md5=beb3066c046de198dee5c79c1739714b (from https://pypi.python.org/simple/python-bitcoinlib/), version: 0.2.1
  Ignoring link https://pypi.python.org/packages/source/p/python-bitcoinlib/python-bitcoinlib-0.1.1.tar.gz#md5=b0dd501ac3f961401327ca4320946218 (from https://pypi.python.org/simple/python-bitcoinlib/), version 0.1.1 doesn't match ==0.3.0
  Ignoring link https://pypi.python.org/packages/source/p/python-bitcoinlib/python-bitcoinlib-0.2.0.tar.gz#md5=2a87f139db530ad299a123ddba8b981f (from https://pypi.python.org/simple/python-bitcoinlib/), version 0.2.0 doesn't match ==0.3.0
  Ignoring link https://pypi.python.org/packages/source/p/python-bitcoinlib/python-bitcoinlib-0.2.1.tar.gz#md5=beb3066c046de198dee5c79c1739714b (from https://pypi.python.org/simple/python-bitcoinlib/), version 0.2.1 doesn't match ==0.3.0
  Could not find a version that satisfies the requirement python-bitcoinlib==0.3.0 (from counterparty-lib) (from versions: 0.1.1, 0.2.0, 0.2.1)
Cleaning up...
  Removing temporary dir C:\Users\rippler\AppData\Local\Temp\pip_build_rippler...
No distributions matching the version for python-bitcoinlib==0.3.0 (from counterparty-lib)
Exception information:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python34\lib\site-packages\pip\req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "C:\Python34\lib\site-packages\pip\index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
pip.exceptions.DistributionNotFound: No distributions matching the version for python-bitcoinlib==0.3.0 (from counterparty-lib)
```

**Comment by btcdrak** [comment]
Shouldn't you be using `pip3` as in `pip3 install counterparty-lib`?

**Comment by rippler** [comment]
I should if I had Python 2.7, but (unlike Ubuntu 14.04, for example) Windows ships without Python 2.x preinstalled so it's a good habit to use `pip3`, but in this case not mandatory (you can see `C:\Python34\lib\site-packages\pip\index.py` towards the end of my log above).

On Windows if you have multiple Python instances, then it depends on which one is in your PATH. On another system I have the both but I default to v3.4:
```
c:\Python34\Scripts>pip3 -V
pip 1.4.1 from c:\python34\lib\site-packages\pip-1.4.1-py3.4.egg (python 3.4)
c:\Python34\Scripts>pip -V
pip 1.4.1 from c:\python34\lib\site-packages\pip-1.4.1-py3.4.egg (python 3.4)

```

**Comment by rippler** [comment]
I have another Windows system (Windows x64, Python 3.4.2, same as above) where python-bitcoinlib 0.3.0 is installed. I don't remember how it got there, but if I search for the package I get the same answer that it is not available.

```
c:\Python34\Scripts>python -V
Python 3.4.2

c:\Python34\Scripts>pip search python-bitcoinlib
python-bitcoinlib         - This python library provides an easy interface to
                            the Bitcoin data structures and protocol.
  INSTALLED: 0.3.0
  LATEST:    0.2.1

c:\Python34\Scripts>pip -V
pip 1.4.1 from c:\python34\lib\site-packages\pip-1.4.1-py3.4.egg (python 3.4)

```

**Comment by btcdrak** [comment]
pip screws up occassionally. Network issues or whatever. Try rerunning.

**Comment by rippler** [comment]
Retried on 2 systems, no joy. 
Weird, v0.3.0 is currently not even listed:
https://pypi.python.org/pypi/python-bitcoinlib

I got the source and installed it manually.
https://github.com/petertodd/python-bitcoinlib/archive/python-bitcoinlib-v0.3.0.zip
Then used `pip` to install `counterparty-lib`, it installs fine.

I don't know if I should try later or the package has been unlisted (or not yet listed, in case I installed it manually on the other system as well).

**Comment by rippler** [comment]
It seems  `--alow-external` needs to be added before 
https://github.com/CounterpartyXCP/counterpartyd/blob/master/pip-requirements.txt#L34
Windows doesn't give a hint of that.

**Comment by adamkrellenstein** [comment]
@rippler, we're not using `pip-requirements.txt` any more.

This line is the problem: https://github.com/CounterpartyXCP/counterpartyd/blob/develop/setup.py#L77-L79

**Comment by ouziel-slama** [comment]
see https://github.com/petertodd/python-bitcoinlib/issues/36

`setup.py` works well on Linux, but on Windows the `--allow-external` and `allow-unverfied` options are buggy. Until Peter Todd fixes the problem, Windows users have to install manually  `python-bitcoinlib`.

**Comment by adamkrellenstein** [comment]
Whoa, yuck!

Mentioned problem in docs: 80421b8d92d6d296d9fcdf7206613f3484817a99

**Comment by rippler** [comment]
@adamkrellenstein I didn't know that pip-reqs was retired...

I still like the pip approach:

* `cd c:\python34; notepad pip-bitcoinlib.txt`:
* paste this into the new file:
```
--allow-external
https://github.com/petertodd/python-bitcoinlib/archive/python-bitcoinlib-v0.3.0.zip
```

* Install 
```
C:\Python34>pip3 install -r pip-bitcoinlib.txt
Downloading/unpacking https://github.com/petertodd/python-bitcoinlib/archive/python-bitcoinlib-v0.3.0.zip (from -r pip-bitcoinlib.txt (line 2))
  Downloading python-bitcoinlib-v0.3.0.zip (unknown size): 111kB downloaded
  Running setup.py egg_info for package from https://github.com/petertodd/python-bitcoinlib/archive/python-bitcoinlib-v0.3.0.zip

Installing collected packages: python-bitcoinlib
  Running setup.py install for python-bitcoinlib

Successfully installed python-bitcoinlib
Cleaning up...

C:\Python34>pip3 list
appdirs (1.4.0)
...
python-bitcoinlib (0.3.0)
...
```

Seems easier for newbies and could be added to `setup.py` (@robby-dermody).

**Comment by adamkrellenstein** [comment]
All of the dependencies are now in `setup.py`.

I don't see any reason to create a new file. That's four commands instead of just one: https://github.com/CounterpartyXCP/Documentation/blob/master/Installation/windows.md
