### ISSUE TITLE
counterparty-lib v9.49.4: No module named 'counterparty'

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#662]
* Win 7 x64
* Python 3.4.2 32-bit

```
c:\Python34\Scripts>pip list counterparty-lib
appdirs (1.4.0)
apsw (3.8.5.post1)
argparse (1.3.0)
bip32utils (0.1)
bitcoin (1.1.23)
bitcoin-python (0.3)
certifi (14.5.14)
colorama (0.3.3)
colorlog (2.4.0)
counterparty-cli (1.0.0)
counterparty-lib (9.49.4)

c:\Python34\Scripts>pip -V
pip 1.4.1 from c:\python34\lib\site-packages\pip-1.4.1-py3.4.egg (python 3.4)
```

When I run the client:

```
c:\Python34\Scripts>..\python.exe counterparty-client --help
Traceback (most recent call last):
  File "counterparty-client", line 10, in <module>
    from counterpartycli import client
  File "c:\Python34\lib\site-packages\counterpartycli\client.py", line 18, in <module>
    from counterpartycli import util
  File "c:\Python34\lib\site-packages\counterpartycli\util.py", line 20, in <module>
    from counterparty.lib import config
ImportError: No module named 'counterparty'

```

**Comment by rippler** [comment]
I figured this out: this happens because `counterparty-cli` doesn't handle deps correctly, so I opened a bug there: https://github.com/CounterpartyXCP/counterparty-cli/issues/10
Until this is fixed, there's workaround at the bottom of that issue: in short first install the CLI, then re-install the LIB package.

**Comment by adamkrellenstein** [comment]
No, the problem is you're working with an old version of counterparty-cli (before the rename of the `counterparty-lib` library from `counterparty` to `counterpartylib`.
