### ISSUE TITLE
No distributions matching the version for counterparty-lib 9.49.4rc3

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#672]
* Win 7, Python 3.4.2
* uninstalled yesterday's versions (and python-bitcoinlib 0.3.0) and 
* installed python-bitcoinlib-0.2.1. 

But now I cannot install `counterparty-lib` any more. Why is that?

```
C:\Windows\System32>pip3 install counterparty-lib
Downloading/unpacking counterparty-lib
  Could not find a version that satisfies the requirement counterparty-lib (from versions: 9.49.4rc3, 9.49.4rc4)
Cleaning up...
No distributions matching the version for counterparty-lib```

**Comment by adamkrellenstein** [comment]
You did `sudo pip3 uninstall counterparty-lib`?

**Comment by rippler** [comment]
> Win 7, Python 3.4.2

Yes, uninstalled, checked the list, empty.
Full pip log of above error:

```
C:\Python34\Scripts\pip3 run on 01/27/15 01:35:40
Downloading/unpacking counterparty-lib

  Getting page https://pypi.python.org/simple/counterparty-lib/
  URLs to search for versions for counterparty-lib:
  * https://pypi.python.org/simple/counterparty-lib/
  Analyzing links from page https://pypi.python.org/simple/counterparty-lib/
    Found link https://pypi.python.org/packages/source/c/counterparty-lib/counterparty-lib-9.49.4rc3.tar.gz#md5=8dc0d320a4853efe655f3fb5ed7395e8 (from https://pypi.python.org/simple/counterparty-lib/), version: 9.49.4rc3
    Found link https://pypi.python.org/packages/source/c/counterparty-lib/counterparty-lib-9.49.4rc4.tar.gz#md5=dac0826f9bfd7e385a6fd815967724ed (from https://pypi.python.org/simple/counterparty-lib/), version: 9.49.4rc4
  Ignoring link https://pypi.python.org/packages/source/c/counterparty-lib/counterparty-lib-9.49.4rc3.tar.gz#md5=8dc0d320a4853efe655f3fb5ed7395e8 (from https://pypi.python.org/simple/counterparty-lib/), version 9.49.4rc3 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/c/counterparty-lib/counterparty-lib-9.49.4rc4.tar.gz#md5=dac0826f9bfd7e385a6fd815967724ed (from https://pypi.python.org/simple/counterparty-lib/), version 9.49.4rc4 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement counterparty-lib (from versions: 9.49.4rc3, 9.49.4rc4)

Cleaning up...

  Removing temporary dir C:\Users\hal_AD~1\AppData\Local\Temp\pip_build_rippler...
No distributions matching the version for counterparty-lib

Exception information:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\basecommand.py", line 134, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\commands\install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\req.py", line 1085, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\index.py", line 309, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
pip.exceptions.DistributionNotFound: No distributions matching the version for counterparty-lib
```

**Comment by adamkrellenstein** [comment]
It says in the error, you need to use `--pre` to allow pre-releases?

**Comment by rippler** [comment]
Damn, I didn't notice that all the way to the right with word wrap disabled.
Yesterday I was wondering about this same issue (why I couldn't install RC1) as well.
Funny thing earlier is I also tried to install `counterparty-cli` to "make sure" I'm not making any mistakes and it failed as well, then I was sure it was a bug ;-)

**Comment by adamkrellenstein** [comment]
@rippler, pip is not super intuitive. :/

Yeah, there were problems yesterday, but I think I've got them all resolved now! (Part of the trick was correctly naming release candidates.)
