### ISSUE TITLE
counterparty-server keep crashing

### ISSUE THREAD

**Issue by cryptodock** [CounterpartyXCP/counterpartyd#676]
So counterparty-server keep crashing on Ubuntu 14.04.01 dedicated server, the errors show something related to internet, however my ssh session to the box never times out so I guess the problem with not my box, anyone any ideas ? this happen few times already.
```
2015-01-28-T01:45:16-0500 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 542, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 396, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 618, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 592, in urlopen
    raise MaxRetryError(self, url, e)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='counterpartyxcp.github.io', port=443): Max retries exceeded with url: /counterparty-lib/protocol_changes.json (Caused by <class 'ConnectionResetEr$

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/check.py", line 131, in version
    response = requests.get(host, headers={'cache-control': 'no-cache'})
  File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='counterpartyxcp.github.io', port=443): Max retries exceeded with url: /counterparty-lib/protocol_changes.json (Caused by <class 'ConnectionRese$

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 11, in <module>
    sys.exit(server_main())
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 14, in server_main
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 170, in main
    server.start_all(db)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/server.py", line 351, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/blocks.py", line 956, in follow
    check.version()
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/check.py", line 138, in version
    raise VersionError('Unable to check version. How’s your Internet access?')
counterpartylib.lib.check.VersionError: Unable to check version. How’s your Internet access?
```

**Comment by adamkrellenstein** [comment]
This is really almost certainly your network connection. SSH is just being more forgiving than `requests`.

**Comment by adamkrellenstein** [comment]
Still, it might be a good idea to make the server stay running when the Internet goes down: https://github.com/CounterpartyXCP/counterpartyd/issues/677
