### ISSUE TITLE
counterparty-lib 9.49.4rc4 reinstall fails due to old counterparty-server directory

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#678]
The directory is empty, by the way. I just installed, uninstalled and attempted to install again.
```
Installing counterparty-server.exe.manifest script to C:\Python34\Scripts

writing list of installed files to 'C:\Users\HAL\AppData\Local\Temp\pip-yvpcea74-record\install-record.txt'

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\Users\HAL\AppData\Local\Temp\pip_build_rippler\counterparty-cli\setup.py", line 166, in <module>

    os.makedirs(new_server_configdir)

  File "C:\Python34\lib\os.py", line 237, in makedirs

    mkdir(name, mode)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\HAL_\\AppData\\Roaming\\Counterparty\\counterpart
y-server'

```

**Comment by ouziel-slama** [comment]
Robby fixed this here: https://github.com/CounterpartyXCP/counterparty-cli/commit/41ed197f12f73379f4144c2eca902fe9e14e1420
