### ISSUE TITLE
9.49.4rc5 upgrade fails

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#681]
* Win 7
* 9.49.4rc4

```
pip3 install --pre --upgrade counterparty-lib
...
    Using c:\python34\lib\site-packages
    Finished processing dependencies for counterparty-lib==9.49.4rc5
    To complete the installation you have to install APSW: https://github.com/rogerbinns/apsw/releases
    To complete the installation you have to install Serpent: https://github.com/ethereum/serpent
  Could not find .egg-info directory in install record for counterparty-lib from https://pypi.python.org/packages/source/c/counterparty-lib/counterpar
ty-lib-9.49.4rc5.tar.gz#md5=ad23478ce289e84a7e02772acf3f2939 in c:\python34\lib\site-packages
Cleaning up...
Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\basecommand.py", line 134, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\commands\install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\req.py", line 1298, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\req.py", line 668, in install
    os.remove(record_filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\hal_AD~1\\AppData\\Local\\T
emp\\pip-a9bje5ja-record\\install-record.txt'

Storing complete log in C:\Users\hal_ADMIN\pip\pip.log
```
From pip.log:
```
    Using c:\python34\lib\site-packages

    Finished processing dependencies for counterparty-lib==9.49.4rc5

    writing list of installed files to 'C:\Users\hal_AD~1\AppData\Local\Temp\pip-a9bje5ja-record\install-record.txt'
    running install_apsw
    To complete the installation you have to install APSW: https://github.com/rogerbinns/apsw/releases

    running install_serpent
    To complete the installation you have to install Serpent: https://github.com/ethereum/serpent

    running move_old_db
  Could not find .egg-info directory in install record for counterparty-lib from https://pypi.python.org/packages/source/c/counterparty-lib/counterparty-lib-9.49.4rc5.tar.gz#md5=ad23478ce289e84a7e02772acf3f2939 in c:\python34\lib\site-packages
```

**Comment by adamkrellenstein** [comment]
Try uninstalling and reinstalling.

**Comment by rippler** [comment]
Will do, I just wanted to log this issue with the upgrade scenario

**Comment by adamkrellenstein** [comment]
`pip` seems to handle upgrades of pre-releases poorly? :/

**Comment by rippler** [comment]
Same thing when re-installing. It does install, but because of https://github.com/CounterpartyXCP/counterparty-cli/issues/16 I can't install `counterparty-cli` to see whether it's installed correctly (presumably yes, it's listed as installed and another re-install says all reqs are already satisfied).

**Comment by rippler** [comment]
This time I looked the pip.log. 
While the second path used by PIP seems randomized, the first is static. 
I don't know if it can be randomized as the second, or if it's just a PIP thing.

```
  Running setup.py install for counterparty-lib

    Running command C:\Python34\python.exe -c "import \
setuptools;__file__='C:\\Users\\DIR\\AppData\\Local\\Temp\\pip_build_rippler\\counterparty-\
lib\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record \
C:\Users\DIR\AppData\Local\Temp\pip-gj_tx31r-record\install-record.txt --single-version-externally-\
managed
```
