### ISSUE TITLE
Unicode char prevents help output from displaying

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#682]
* FreeBSD 10.1 x86-54, bash shell
* Python 3.4
* Seen (so far) only in `--help` output (`RC4`). Server (maybe) can run, I haven't tried that yet.

```
[root@freebsd10 ~/pip-1.5.6]# counterparty-server --help
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 11, in <module>
    sys.exit(server_main())
  File "/usr/local/lib/python3.4/site-packages/counterpartycli/__init__.py", line 14, in server_main
    server.main()
  File "/usr/local/lib/python3.4/site-packages/counterpartycli/server.py", line 65, in main
    args = parser.parse_args()
  File "/usr/local/lib/python3.4/argparse.py", line 1721, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.4/argparse.py", line 1753, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/lib/python3.4/argparse.py", line 1959, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/lib/python3.4/argparse.py", line 1899, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/lib/python3.4/argparse.py", line 1827, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.4/argparse.py", line 1016, in __call__
    parser.print_help()
  File "/usr/local/lib/python3.4/argparse.py", line 2352, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/local/lib/python3.4/argparse.py", line 2358, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2010' in position 2794: ordinal not in range(128)
```

**Comment by adamkrellenstein** [comment]
Unicode terminal support is required.
