### ISSUE TITLE
Transient error on 9.49.4rc7 startup and "Cannot assign requested address"

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#688]
Perhaps times out too soon... `bitcoind` is running on another node, but it's close by so it shouldn't time out so soon (it happens less than a second after it starts). Also there's a "Cannot assign requested address" error. 
The both appear only right after I start server and not later. Server runs fine, I can't see other issues with it. This is with `--verbose`, as you can see.

* Ubuntu 14.10 <==== !
* counterparty-lib 9.49.4rc7

```
[DEBUG] Checking backend state.
[INFO] Starting API Server.
[DEBUG] Creating connection to `/home/rippler/.local/share/counterparty/counterparty.9.testnet.db`.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4rc7-py3.4.egg/counterpartylib/lib/api.py", line 701, in run
    http_server.listen(config.RPC_PORT, address=config.RPC_HOST)
  File "/usr/local/lib/python3.4/dist-packages/tornado-4.1b2-py3.4-linux-i686.egg/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.4/dist-packages/tornado-4.1b2-py3.4-linux-i686.egg/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4rc7-py3.4.egg/counterpartylib/lib/api.py", line 705, in run
    raise APIError("Cannot start the API subsystem. Is server already running, or is something else listening on port {}?".format(config.RPC_PORT))
counterpartylib.lib.api.APIError: Cannot start the API subsystem. Is server already running, or is something else listening on port 14000?

[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[INFO] Client minor version number mismatch (0 â  49).
[INFO] Reparsing all transactions.
[DEBUG] Checking version.
[DEBUG] Version check passed.
[INFO] Block (reâparse): 310000

```

**Comment by ouziel-slama** [comment]
hum..seems you have already an RPC server running on the same port.

**Comment by rippler** [comment]
No I don't, unless server is already configured to automatically kill it (because the error takes 0.1 second after which the server immediately proceeds and starts up). It's probably too fast for the system and/or doesn't wait long enough for the system to respond). 
Not a big deal (and not visible without `--verbose`), though.

**Comment by adamkrellenstein** [comment]
Yep

**Comment by ouziel-slama** [comment]
hum.. not visible not means not here ;-) if only the synchronisation start correctly and not the RPC server we have here a real problem.

**Comment by adamkrellenstein** [comment]
@rippler, I think @ouziel-slama's right---check that there isn't already a server running elswhere.

**Comment by adamkrellenstein** [comment]
`netstat -anp | grep 14000`, or whatever

**Comment by rippler** [comment]
I was sure it wasn't, but I checked again. Nothing. 

```
rippler@linux-c254:~> netstat -an | grep 14000
rippler@linux-c254:~> ps -ef | grep counter
rippler  14105 13865  0 22:33 pts/1    00:00:00 grep --color=auto counter
rippler@linux-c254:~> counterparty-server start
[INFO] Running v1.0.0rc7 of counterparty-server.
[INFO] Running v9.49.3 of counterparty-lib.
[INFO] Acquiring lock.
[INFO] Connecting to database.
[INFO] Connecting to backend.
[INFO] Starting API Server.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/counterparty_lib-9.49.4rc7-py3.4.egg/counterpartylib/lib/api.py", line 701, in run
    http_server.listen(config.RPC_PORT, address=config.RPC_HOST)
  File "/usr/lib64/python3.4/site-packages/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib64/python3.4/site-packages/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/site-packages/counterparty_lib-9.49.4rc7-py3.4.egg/counterpartylib/lib/api.py", line 705, in run
    raise APIError("Cannot start the API subsystem. Is server already running, or is something else listening on port {}?".format(config.RPC_PORT))
counterpartylib.lib.api.APIError: Cannot start the API subsystem. Is server already running, or is something else listening on port 14000?

```

**Comment by adamkrellenstein** [comment]
If you're running on mainnet, you need `netstat -anp | grep 4000`.

**Comment by rippler** [comment]
It works fine, it just throws those errors at the very beginning (in the first second after `counterparty-server start`), that's all. After that it works fine.
It's not causing any trouble except that those errors appear in the logs (with and without `--verbose`).
It doesn't seem Counterparty-related to me, more like upstream error (Tornado?).

**Comment by adamkrellenstein** [comment]
Closing for now, then.
