### ISSUE TITLE
Unable to set log file path in server.conf

### ISSUE THREAD

**Issue by mtbitcoin** [CounterpartyXCP/counterpartyd#700]
This on a windows box. When attempting to set the server.conf option for log-file, it is throwing a Permission Denied error (even though the folder has full permissions)

# the path to the server log file
log-file = c:\logFolder

===
Traceback (most recent call last):
  File "counterparty-server.py", line 17, in <module>
  File "counterparty-server.py", line 16, in server_main
  File "C:\counterparty\counterparty-cli\counterpartycli\server.py", line 109, in main
  File "C:\counterparty-cli-win32-1.0.0\library\counterpartylib\server.py", line 301, in initialise
    log.set_up(root_logger, verbose=verbose, logfile=config.LOG)
  File "C:\counterparty-cli-win32-1.0.0\library\counterpartylib\lib\log.py", line 36, in set_up
    fileh = util_windows.SanitizedRotatingFileHandler(logfile, maxBytes=max_log_size, backupCount=5)

  File "C:\Python34\lib\logging\handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python34\lib\logging\handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python34\lib\logging\__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python34\lib\logging\__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: 'c:\\logFolder'

**Comment by ouziel-slama** [comment]
hum.. `log-file` should contains a filename not a folder.. however it not should be a problem (`logFolder` can be a file name) *unless* the folder 'c:\logFolder' already exists ?

**Comment by mtbitcoin** [comment]
yes. it look like it has to be the full path including the log file name. 

As for the standalone binaries (this one https://github.com/CounterpartyXCP/counterparty-cli/releases/tag/v1.0.0 ?? ). It complains about a missing package...json file. I have to first git and install the python counterparty-cli tools and run that once. Only then can I run the standalone libraries at https://github.com/CounterpartyXCP/counterparty-cli/releases/tag/v1.0.0

**Comment by ouziel-slama** [comment]
great. 
I opened an issue for the second problem: https://github.com/CounterpartyXCP/counterparty-cli/issues/20 thanks.
