### ISSUE TITLE
Unhandled Exception, OverflowError: int too big to convert - when parsing transactions

### ISSUE THREAD

**Issue by snitko** [CounterpartyXCP/counterpartyd#731]
When running `counterparty-server --verbose start` getting this at some point:

    [DEBUG] Skipping transaction: bbad96ec972b976d9d7bd726e4d22a8fbcdb20121697e95991035781b535167a
    [ERROR] Unhandled Exception
    Traceback (most recent call last):
      File "/usr/local/bin/counterparty-server", line 9, in <module>
        load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-server')()
      File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/__init__.py", line 16, in server_main
        server.main()
      File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/server.py", line 123, in main
        server.start_all(db)
      File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/server.py", line 348, in start_all
        blocks.follow(db)
      File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/blocks.py", line 998, in follow
        parse_block(db, block_index, block_time)
      File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/blocks.py", line 151, in parse_block
        parse_tx(db, tx)
      File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/blocks.py", line 85, in parse_tx
        send.parse(db, tx, message)
      File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/messages/send.py", line 43, in parse
        return send1.parse(db, tx, message)
      File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/messages/versions/send1.py", line 122, in parse
        cursor.execute(sql, bindings)
    OverflowError: int too big to convert

**Comment by karlkeefer** [comment]
Same issue here, counterparty crashing each time it restarts itself.

**Comment by ouziel-slama** [comment]
see here: https://github.com/CounterpartyXCP/counterpartyd/pull/732

**Comment by adamkrellenstein** [comment]
Solved.

**Comment by snitko** [comment]
It's very weird that upon update, it started parsing transactions back from 2014. Is this supposed to be like that? I don't want to be downloading all that again.

**Comment by deweller** [comment]
All transactions need to be re-parsed according to `https://counterpartyxcp.github.io/counterpartyd/protocol_changes.json`.  This isn't the same as re-downloading all the transactions.

On my VM, this looks like it will take 15-30 minutes.
