### ISSUE TITLE
Exception in unpack()

### ISSUE THREAD

**Issue by ArtemKo7v** [CounterpartyXCP/counterpartyd#735]
tx hash: 8db88dd652c118f71a043e62399593573c2d74ed5cd6735b3ba9ad9ca1043a09

method: unpack,
params: {
   data_hex: "0000001404a243006a851298000000174876e800010000000000000000000474657374"
}

```
2015-03-25-T13:09:06+0000 [ERROR] API Exception: {'message': "'lib.messages.bet'", 'type': 'KeyError', 'args': ('lib.messages.bet',)}
Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/json_rpc-1.8.3-py3.4.egg/jsonrpc/manager.py", line 104, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.50.0-py3.4.egg/counterpartylib/lib/api.py", line 642, in unpack
    if message_type_id == sys.modules['lib.messages.{}'.format(message_type)].ID:
KeyError: 'lib.messages.bet'
2015-03-25-T13:09:07+0000 [ERROR] API Exception: {'message': 'No blocks found.', 'type': 'DatabaseError', 'args': ('No blocks found.',)}
Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/json_rpc-1.8.3-py3.4.egg/jsonrpc/manager.py", line 104, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.50.0-py3.4.egg/counterpartylib/lib/api.py", line 509, in get_block_info
    raise exceptions.DatabaseError('No blocks found.')
counterpartylib.lib.exceptions.DatabaseError: No blocks found.
2015-03-25-T13:09:08+0000 [ERROR] API Exception: {'message': 'No blocks found.', 'type': 'DatabaseError', 'args': ('No blocks found.',)}
Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/json_rpc-1.8.3-py3.4.egg/jsonrpc/manager.py", line 104, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.50.0-py3.4.egg/counterpartylib/lib/api.py", line 509, in get_block_info
    raise exceptions.DatabaseError('No blocks found.')
counterpartylib.lib.exceptions.DatabaseError: No blocks found.
```

**Comment by adamkrellenstein** [comment]
This section has recently been rewritten: https://github.com/CounterpartyXCP/counterpartyd/blob/develop/counterpartylib/lib/api.py#L606-L617
