### ISSUE TITLE
Exception on executing get_tx_info with a non Counterparty transaction hash

### ISSUE THREAD

**Issue by ArtemKo7v** [CounterpartyXCP/counterpartyd#736]
method: get_tx_info,
params: {tx_hex:"bdf2e93abaae1c2102d379edfe568376f696a9c999113c5f47ddf15f7a339030"}

```
2015-03-25-T09:40:34+0000 [ERROR] API Exception: {'message': 'Asked to read 32 bytes, but only got 27', 'type': 'SerializationTruncationError', 'args': ('Asked to read 32 bytes, but only got 27',)}
Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/json_rpc-1.8.3-py3.4.egg/jsonrpc/manager.py", line 104, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.50.0-py3.4.egg/counterpartylib/lib/api.py", line 630, in get_tx_info
    source, destination, btc_amount, fee, data = blocks.get_tx_info(tx_hex)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.50.0-py3.4.egg/counterpartylib/lib/blocks.py", line 361, in get_tx_info
    tx_info = get_tx_info2(tx_hex, block_parser=block_parser)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.50.0-py3.4.egg/counterpartylib/lib/blocks.py", line 492, in get_tx_info2
    ctx = backend.deserialize(tx_hex)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_lib-9.50.0-py3.4.egg/counterpartylib/lib/backend/__init__.py", line 49, in deserialize
    return bitcoinlib.core.CTransaction.deserialize(binascii.unhexlify(tx_hex))
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/python_bitcoinlib-0.3.0-py3.4.egg/bitcoin/core/serialize.py", line 115, in deserialize
    r = cls.stream_deserialize(fd)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/python_bitcoinlib-0.3.0-py3.4.egg/bitcoin/core/__init__.py", line 325, in stream_deserialize
    vin = VectorSerializer.stream_deserialize(CTxIn, f)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/python_bitcoinlib-0.3.0-py3.4.egg/bitcoin/core/serialize.py", line 247, in stream_deserialize
    r.append(inner_cls.stream_deserialize(f))
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/python_bitcoinlib-0.3.0-py3.4.egg/bitcoin/core/__init__.py", line 194, in stream_deserialize
    prevout = COutPoint.stream_deserialize(f)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/python_bitcoinlib-0.3.0-py3.4.egg/bitcoin/core/__init__.py", line 135, in stream_deserialize
    hash = ser_read(f,32)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/python_bitcoinlib-0.3.0-py3.4.egg/bitcoin/core/serialize.py", line 81, in ser_read
    raise SerializationTruncationError('Asked to read %i bytes, but only got %i' % (n, len(r)))
bitcoin.core.serialize.SerializationTruncationError: Asked to read 32 bytes, but only got 27
```

**Comment by ArtemKo7v** [comment]
My fault, this method awaits raw tx hex in tx_hex param.
It works with CP transactions, but still fails with an exception, if non-CP transaction hex given.

**Comment by adamkrellenstein** [comment]
I fixed that line---that was an error. (It shouldn't have said 'hash'.) https://github.com/CounterpartyXCP/Documentation/commit/1fc9681c604c623f5d5ac138e9f4224413aa8b96

I also handled the case for non-Counterparty transactions.
