### ISSUE TITLE
BTCPay causes an exception

### ISSUE THREAD

**Issue by ArtemKo7v** [CounterpartyXCP/counterpartyd#747]
http://blockscan.com/orderInfo/11620218#ordermatches

Node A:

```
# sudo su -s /bin/bash -c 'counterparty-client btcpay --source 17FKi2nNYtq6VGjayArSNJ9MPQqZJC3j9U --order-match-id 255a7dcb95a4b5ec05dacd0850915934637d8cc2f88bd811d1b72944d7857d5b_994851318de11a0d1228d615f14198f109a93d9a92acbb0fec28cf450def5c73' xcpd
[INFO] Transaction (unsigned): 0100000002735cef0d45cf28ec0fbbac929a3da909f19841f115d628120d1ae18d31514899010000001976a914448631c051d0f6c61fdd577d4ccb96f51262d8d188acffffffffa126412f2f3a91a2b00b8794e9d130d2c3751c4212eba7cbd84281456540fffe000000001976a914448631c051d0f6c61fdd577d4ccb96f51262d8d188acffffffff04b0ad0100000000001976a91436d371a9d4156430d56b9ac72b50193b38d30d2e88ac781e00000000000069512103bb20643509a27abfe83a0173597c9b9d577f05f5f72d10b83d3354e9902d0f7c2102874d45b30d1baf14199e128207b4d67b6cd7191b4f9d43cfda25766d44940cfc210246d2c2c511f1ea843f607edb8050498d1b3e74b9d952a2bc043a5c5147cc3ef853ae781e000000000000695121039120643509a27abfe8933ce9c0f57aef70c26e0516c796063563c5b0a44e720321020b8fbd38d50a7ea330dac5077aef4f333de694fa559051e70c30872cdc6505e2210246d2c2c511f1ea843f607edb8050498d1b3e74b9d952a2bc043a5c5147cc3ef853ae787c0100000000001976a914448631c051d0f6c61fdd577d4ccb96f51262d8d188ac00000000
Sign and broadcast? (y/N) y
Source address not in wallet. Please enter the private key in WIF formar for 17FKi2nNYtq6VGjayArSNJ9MPQqZJC3j9U:*******************
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.1', 'console_scripts', 'counterparty-client')()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.1-py3.4.egg/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.1-py3.4.egg/counterpartycli/client.py", line 722, in main
    args.unsigned)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.1-py3.4.egg/counterpartycli/client.py", line 324, in cli
    signed_tx_hex = sign_tx(unsigned_tx_hex, params['source'])
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.1-py3.4.egg/counterpartycli/client.py", line 302, in sign_tx
    raise exceptions.TransactionError('Could not sign transaction with pybtctool.')
NameError: name 'exceptions' is not defined
```

Node B:

```
# sudo su -s /bin/bash -c 'counterparty-client btcpay --source 17FKi2nNYtq6VGjayArSNJ9MPQqZJC3j9U --order-match-id 255a7dcb95a4b5ec05dacd0850915934637d8cc2f88bd811d1b72944d7857d5b_994851318de11a0d1228d615f14198f109a93d9a92acbb0fec28cf450def5c73' xcpd
[INFO] Running v1.0.0 of counterparty-client.
ERROR:root:Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-client')()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterpartycli/client.py", line 229, in main
    unsigned_hex = messages.compose(args.action, args)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterpartycli/messages.py", line 272, in compose
    return compose_transaction(args, message, param_names)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterpartycli/messages.py", line 265, in compose_transaction
    check_transaction(method, params, unsigned_tx_hex)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterpartycli/messages.py", line 234, in check_transaction
    tx_info = transaction.check_outputs(method, params, tx_hex)
AttributeError: 'module' object has no attribute 'check_outputs'
```

Trying to sign and broadcast transaction generated by btcpay on "Node A" using CounterWallet:

![2015-03-30_1459](https://cloud.githubusercontent.com/assets/2138231/6892346/7611ed08-d6ed-11e4-800c-2adf220d6916.png)

**Comment by ouziel-slama** [comment]
Seems there is 3 different bugs here.
About the second, seems you are using in the Node B the `develop` branch of `counterparty-cli`. To use this branch you need to install the `checktx` branch of `counterparty-lib`.
About the third, I opened an issue in `counterwallet` repo: https://github.com/CounterpartyXCP/counterwallet/issues/721

**Comment by ArtemKo7v** [comment]
BTW, I think there is a mistype here ("formar").
https://github.com/CounterpartyXCP/counterparty-cli/search?utf8=%E2%9C%93&q=formar

**Comment by ouziel-slama** [comment]
@ArtemKo7v: Thank you, I fixed the typo and will push it as soon is possible (get a timeout when trying to push)

About the first problem, there is a two problems in it:
- an import error in `counterparty-cli` (the fix also waits a push)
- a more general problem with `pybtctools` https://github.com/CounterpartyXCP/counterparty-cli/issues/28

**Comment by ouziel-slama** [comment]
see last 3 commits here: https://github.com/CounterpartyXCP/counterparty-cli/commits/develop
