### ISSUE TITLE
Two unhandled exceptions during parse of bootstrap db

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#762]
This occured with counterparty-lib and counterparty-cli on the git master branch and when that failed, the develop branches of both. I have also tried the stable release versions. I am using addrindex, with config parameters that worked previously.

From a freshly extracted bootstrap db image, the error looks like this:

```
$ counterparty-server --database-file ~/.config/counterparty-server/counterpartyd.9.db start
[INFO] Running v1.1.0 of counterparty-server.
[INFO] Running v9.51.0 of counterparty-lib.
[INFO] Acquiring lock.
[INFO] Connecting to database.
[INFO] Connecting to backend.
[INFO] Starting API Server.
[INFO] Client major version number mismatch (0 ≠ 9).
[INFO] Reparsing all transactions.
[INFO] Block (re‐parse): 278270
[INFO] Database minor version number updated.
[INFO] Database version number updated.
[INFO] Resuming parsing.
[INFO] Order: 14wLMb2A9APqrdXJhTQArYLyivmEAf7Y1r ordered 0.0 XCP for <AssetError> in 1000 blocks, with a provided fee of 0.0002 BTC and a required fee of 0.0 BTC (cade6882dd8a1754076d68f41fd8deaf44536c137268d8b87a9c9e7881cfdd08) [invalid: non‐positive give quantity; zero give or zero get; no such asset to get (0)]
[INFO] Order: 1HUhWxhTHxRB99ADagQSqXSTzMsE9uRspc ordered 0.0 XCP for <AssetError> in 1000 blocks, with a provided fee of 0.0002 BTC and a required fee of 0.0 BTC (75fef030cd5c8010b2cdfdd11be51303c3133e2b3dfc5af5c2a7a6f6bbb7f05a) [invalid: non‐positive give quantity; zero give or zero get; no such asset to get (0)]
[INFO] Send: <AssetError> from 1C5VaFLiFsnMfhPyJmuKHPCEQo7Pvi9W3Y to 18tsYVVm4RgHDbSR5JTfemKQF8HBqSfNaG (ec658b2aa56d233ac1781d5298dfa291a023181c7817c883547108b1272e4cb0) [invalid: insufficient funds]
[INFO] Send: 48.0845 XCP from 1NFeBp9s5aQ1iZ26uWyiK2AYUXHxs7bFmB to 1PspV8xQcoWzQEsttQJrYjzW4fazfRh2oA (a23931f026391c7a185b494d73dc3acace649769b3da07c187c285b5a0365b55) [invalid: insufficient funds]
[INFO] Send: <AssetError> from 1NJEmiGdBrBnW5s2c24uMA6QDVMXVKPgDh to 19BBdBeeRRjNQNa8h8bGLT8JBYhjbs4uCm (914e6ed6e58e45a9039315d97424431b895841c2b9db1938f186f889ea93f224) [invalid: insufficient funds]
[INFO] Send: <AssetError> from 1Po1oXMCWobE6kxWr8rJEP1SRq71JSD3t4 to 17unatc1SvSweTtC8ZmBHTxRCY71gPPcgv (31536c7400622d1a455ed61b6d1df3af73bf3d50be7b707879737b3c7d750820) [invalid: insufficient funds]
[INFO] Send: <AssetError> from 1Po1oXMCWobE6kxWr8rJEP1SRq71JSD3t4 to 17unatc1SvSweTtC8ZmBHTxRCY71gPPcgv (414ef343018adcd2717f8cd1bbee1131306183d9072d8a0cf1b687ae7dc5f90c) [invalid: insufficient funds]
[INFO] Send: 22.0 XCP from 1KVMwA6UGgqeQBEJ32fJJPzoipAWiQGekC to 1Po1oXMCWobE6kxWr8rJEP1SRq71JSD3t4 (354398cb9efb131e618bf9febec69cd5d15f989ecf3353bae12ccdd4cccc3885) [invalid: insufficient funds]
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.0', 'console_scripts', 'counterparty-server')()
  File "/usr/lib/python3.4/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 129, in main
    server.start_all(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 358, in start_all
    blocks.follow(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 1008, in follow
    parse_block(db, block_index, block_time)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 160, in parse_block
    new_txlist_hash = check.consensus_hash(db, 'txlist_hash', previous_txlist_hash, txlist)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/check.py", line 73, in consensus_hash
    previous_consensus_hash = list(cursor.execute('''SELECT * FROM blocks WHERE block_index = ?''', (block_index - 1,)))[0][field]
IndexError: list index out of range
```

and sometimes this:

```
$ counterparty-server --database-file ~/.config/counterparty-server/counterpartyd.9.db start
[INFO] Running v1.1.0 of counterparty-server.
[INFO] Running v9.51.0 of counterparty-lib.
[INFO] Acquiring lock.
[INFO] Connecting to database.
[INFO] Connecting to backend.
[INFO] Starting API Server.
[INFO] Resuming parsing.
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.0', 'console_scripts', 'counterparty-server')()
  File "/usr/lib/python3.4/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 129, in main
    server.start_all(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 365, in start_all
    blocks.follow(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 912, in follow
    backend.init_mempool_cache()
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/__init__.py", line 242, in init_mempool_cache
    BACKEND().getrawtransaction_batch(vin_txhash_list, verbose=True)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/addrindex.py", line 182, in getrawtransaction_batch
    batch_responses = rpc_batch(payload)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/addrindex.py", line 85, in rpc_batch
    responses += rpc_call(chunk)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/addrindex.py", line 45, in rpc_call
    raise BackendRPCError('Cannot communicate with backend at `{}`. (server is set to run on {}, is backend?)'.format(url, network))
counterpartylib.lib.backend.addrindex.BackendRPCError: Cannot communicate with backend at `http://bitcoin:jk87A8TLY7FA7bMKCwGCHUpJ5vXeuXePGbbTUchqdHT7TFq@localhost:8332`. (server is set to run on mainnet, is backend?)
```

I am certain that the config parameters for connecting to bitcoind are correct, and that bitcoind is running.

In other cases, counterparty-server ignores the database file even though it is passed correctly as a config parameter. In these cases, the `counterparty-server start` cmd begins parsing from block 278xxx. I think counterparty-server is reverting to parsing from block 278xxx after an error is encountered as outlined above. If I delete the db, re-extract it from tarball and start over the process then it leads to the error messages.

**Comment by ouziel-slama** [comment]
@atweiden : For the first error, it seems that you use an old database. The new name of the database is `counterparty.db` (not `counterpartyd.9.db`). Please try:
`counterparty-server bootstrap` then `counterparty-server start`.

**Comment by atweiden** [comment]
That makes sense, it was an old db.
