### ISSUE TITLE
[btcd] Failed to parse request

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#765]
There is an error with btcd `json: cannot unmarshal array into Go value of type btcjson.Request`:

```
$ counterparty-server start
[INFO] Running v1.1.0 of counterparty-server.
[INFO] Running v9.51.1 of counterparty-lib.
[INFO] Acquiring lock.
[DEBUG] Lock acquired.
[INFO] Connecting to database.
[DEBUG] Creating connection to `.config/counterparty-server/counterparty.db`.
[DEBUG] Checking database integrity.
[INFO] Connecting to backend.
[DEBUG] Starting API Status Poller.
[DEBUG] Creating connection to `.config/counterparty-server/counterparty.db`.
[DEBUG] Checking backend state.
[INFO] Starting API Server.
[DEBUG] Checking version.
[DEBUG] Creating connection to `.config/counterparty-server/counterparty.db`.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[DEBUG] Version check passed.
[DEBUG] Checking database version.
[INFO] Resuming parsing.
[DEBUG] Initialize mempool cache
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.0', 'console_scripts', 'counterparty-server')()
  File "/usr/lib/python3.4/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 912, in follow
    backend.init_mempool_cache()
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/__init__.py", line 237, in init_mempool_cache
    mempool_tx = BACKEND().getrawtransaction_batch(txhash_list, verbose=True)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 125, in getrawtransaction_batch
    batch_responses = rpc_batch(payload)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 74, in rpc_batch
    responses += rpc_call(chunk)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 54, in rpc_call
    raise BackendRPCError('{}'.format(response_json['error']))
counterpartylib.lib.backend.btcd.BackendRPCError: {'message': 'Failed to parse request: json: cannot unmarshal array into Go value of type btcjson.Request', 'code': -32700}
```

This was encountered with the development branch of counterparty-lib and counterparty-cli.

**Comment by ouziel-slama** [comment]
should be fixed with: https://github.com/CounterpartyXCP/counterpartyd/commit/3f874edddfe1da7fcc08fe1143cc35738d31118d
