### ISSUE TITLE
[btcd] KeyError

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#766]
btcd is throwing an error on block 352784 (latest master branch):

```
[INFO] Block: 352783 (5.49s)
[DEBUG] Checking that block 352784 is not an orphan.
[DEBUG] Checking version.
[DEBUG] Checking backend state.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[DEBUG] Version check passed.
[DEBUG] Checking backend state.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[DEBUG] Checking backend state.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/lib/python3.4/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 987, in follow
    raw_transactions = backend.getrawtransaction_batch(txhash_list)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/__init__.py", line 53, in getrawtransaction_batch
    return BACKEND().getrawtransaction_batch(txhash_list, verbose=verbose)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 142, in getrawtransaction_batch
    del(RAW_TRANSACTIONS_CACHE[first_hash])
KeyError: '570cd7086533fe851404842b248c1da793a6d9b2dfc3b47d4aa5b1cb58063391'
```

**Comment by ouziel-slama** [comment]
fixed here: https://github.com/CounterpartyXCP/counterpartyd/commit/90f84eceba1eb784e17ce18926f328169cdf7b33

**Comment by atweiden** [comment]
This allows for parsing past block 352784, but errors out later:

```
[INFO] Block: 352796 (9.15s)
[DEBUG] Checking that block 352797 is not an orphan.
[DEBUG] Checking version.
[DEBUG] Version check passed.
[DEBUG] Checking backend state.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[DEBUG] Checking backend state.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[DEBUG] Checking backend state.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[DEBUG] Checking backend state.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[DEBUG] Checking backend state.
[DEBUG] Backend state check passed.
[DEBUG] Checking database state.
[DEBUG] API Status Poller: Counterparty database is behind backend.
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/lib/python3.4/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 987, in follow
    raw_transactions = backend.getrawtransaction_batch(txhash_list)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/__init__.py", line 53, in getrawtransaction_batch
    return BACKEND().getrawtransaction_batch(txhash_list, verbose=verbose)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 151, in getrawtransaction_batch
    del(RAW_TRANSACTIONS_CACHE[first_hash])
KeyError: '40b068f196f6e0c9a459c32ec08be80ce819d5cd637d7b343e46e01eb57700d9'
```

**Comment by atweiden** [comment]
[strace](http://ix.io/i1n) / Traceback / line 250

**Comment by ouziel-slama** [comment]
hum.. I don't really understand yet how this can happen but should be fixed with https://github.com/CounterpartyXCP/counterpartyd/commit/34d0f9c0e9cb23196219255ba5a8a7ac058db0cd

**Comment by atweiden** [comment]
Fixed, [thanks](https://gist.github.com/atweiden/633fadd8aa7c6a54bead).
