### ISSUE TITLE
[btcd] API exception

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#768]
I was using [counterparty-btcd](https://gist.github.com/atweiden/633fadd8aa7c6a54bead) setup on the develop branch of counterparty-lib:

```
$ counterparty-client --config-file ~/.config/counterparty/client.testnet.conf \
                    --unsigned \
                    --json-output \
                    issuance --source n1LFjn1JVeoSgopz4bhvnb3tS4bjZmgwQK \
                             --asset A1111111111111111111 \
                             --quantity 100000000 \
                             --divisible \
                             --description "description of unnamed asset" \
                             --fee 0.00005
[INFO] Running v1.1.1 of counterparty-client.
ERROR:root:Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-client')()
  File "/usr/lib/python3.4/site-packages/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/client.py", line 230, in main
    unsigned_hex = messages.compose(args.action, args)
  File "/usr/lib/python3.4/site-packages/counterpartycli/messages.py", line 274, in compose
    return compose_transaction(args, message, param_names)
  File "/usr/lib/python3.4/site-packages/counterpartycli/messages.py", line 265, in compose_transaction
    unsigned_tx_hex = util.api(method, params)
  File "/usr/lib/python3.4/site-packages/counterpartycli/util.py", line 92, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "/usr/lib/python3.4/site-packages/counterpartycli/util.py", line 89, in rpc
    raise RPCError('{}'.format(response_json['error']))
counterpartycli.util.RPCError: {'data': {'type': 'BackendRPCError', 'message': '{\'code\': -32602, \'message\': "parameter #2 \'verbose\' must be type int (got bool)"}', 'args': ['{\'code\': -32602, \'message\': "parameter #2 \'verbose\' must be type int (got bool)"}']}, 'code': -32000, 'message': 'Server error'}
```

The counterparty-server log:

```
[DEBUG] Getting outputs.
[DEBUG] Searching raw transactions.
[ERROR] API Exception: {'args': ('{\'code\': -32602, \'message\': "parameter #2 \'verbose\' must be type int (got bool)"}',), 'type': 'BackendRPCError', 'message': '{\'code\': -32602, \'message\': "parameter #2 \'verbose\' must be type int (got bool)"}'}
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 91, in searchrawtransactions
    rawtransactions = rpc('searchrawtransactions', [address, True, 0, 9999999])
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 63, in rpc
    return rpc_call(payload)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 54, in rpc_call
    raise BackendRPCError('{}'.format(response_json['error']))
counterpartylib.lib.backend.btcd.BackendRPCError: {'code': -32602, 'message': "parameter #2 'verbose' must be type int (got bool)"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/jsonrpc/manager.py", line 108, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/api.py", line 449, in create_method
    return compose_transaction(db, name=tx, params=transaction_args, **common_args)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/api.py", line 313, in compose_transaction
    fee_provided=fee_provided)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/transaction.py", line 395, in construct
    unspent = backend.get_unspent_txouts(source, unconfirmed=allow_unconfirmed_inputs, multisig_inputs=multisig_inputs)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/__init__.py", line 148, in get_unspent_txouts
    raw_transactions = searchrawtransactions(source, unconfirmed=True)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/__init__.py", line 49, in searchrawtransactions
    return BACKEND().searchrawtransactions(address, unconfirmed=unconfirmed)
  File "/usr/lib/python3.4/site-packages/counterpartylib/lib/backend/btcd.py", line 93, in searchrawtransactions
    raise BackendRPCError(str(e))
counterpartylib.lib.backend.btcd.BackendRPCError: {'code': -32602, 'message': "parameter #2 'verbose' must be type int (got bool)"}
```

**Comment by ouziel-slama** [comment]
Fixed here: https://github.com/CounterpartyXCP/counterpartyd/commit/db9757068d81e9bb8aa6a47008740638f937fefc

**Comment by atweiden** [comment]
Confirmed, it works.

I was trying to issue a numeric asset on testnet. Do I need to specify `--asset A1111111111111111111` on the cmdline? Can it be generated at random?

```
counterparty-client --config-file ~/.config/counterparty/client.testnet.conf \
                    --unsigned \
                    --json-output \
                    issuance --source n1LFjn1JVeoSgopz4bhvnb3tS4bjZmgwQK \
                             --asset A1111111111111111111 \
                             --quantity 100000000 \
                             --divisible \
                             --description "description of unnamed asset" \
                             --fee 0.00005
[INFO] Running v1.1.1 of counterparty-client.
[INFO] Transaction (unsigned): 0100000001635817c8f8302d791e4facac61f5b79c0455c7ec5a7cba76bc17c4fbb3e
69f12000000001976a914d95c804e2ae5e9433ddf56ba46dd67e3472c1fe188acffffffff03781e000000000000695121026681ff5b9a2fb7e3967ea6cfab68533f2f71ec1fa4a39f0483d2ead49a47aee4210271ca56293dbdb5d51dff95f200a1a0825cb99c8bb95498dbd2f55af57a32b323210292dcd8256bc8c8b53a07c2ecf341ea5bf15202abd996544afe12315cdd1b069e53ae781e000000000000695121025581ff5b9a2fb7e3965ec7bccc024c4a845a286e63a3bc8271bd2bd49a46aeb0210271ca56293dbdb5d5019bf08163d3c9f228d0f3e5993bfefba79b34941757d757210292dcd8256bc8c8b53a07c2ecf341ea5bf15202abd996544afe12315cdd1b069e53ae48ac9b01000000001976a914d95c804e2ae5e9433ddf56ba46dd67e3472c1fe188ac00000000
```

**Comment by adamkrellenstein** [comment]
@atweiden, you can generate it at random (the space of asset numbers is large enough that there won't be any collisions), but Counterparty doesn't do it for you.

**Comment by adamkrellenstein** [comment]
@atweiden, you can generate it at random (the space of asset numbers is large enough that there won't be any collisions), but Counterparty doesn't do it for you.
